/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TatePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/view.ts
var import_obsidian = require("obsidian");

// src/sync/DebounceQueue.ts
var DebounceQueue = class {
  constructor(delayMs = 500) {
    this.timer = null;
    this.pending = null;
    this.delayMs = delayMs;
  }
  schedule(fn) {
    this.pending = fn;
    if (this.timer !== null) clearTimeout(this.timer);
    this.timer = setTimeout(async () => {
      this.timer = null;
      const f = this.pending;
      this.pending = null;
      if (f) await f();
    }, this.delayMs);
  }
  // ペンディング中のコールバックをキャンセルせず即時実行する（ビューを閉じる際などに使用）
  async flushAndExecute() {
    if (this.timer !== null) {
      clearTimeout(this.timer);
      this.timer = null;
    }
    if (this.pending) {
      const f = this.pending;
      this.pending = null;
      await f();
    }
  }
};

// src/sync/SyncCoordinator.ts
var SyncCoordinator = class {
  constructor(vault, getEditorValue, setEditorValue, debounceMs = 500) {
    this.vault = vault;
    this.getEditorValue = getEditorValue;
    this.setEditorValue = setEditorValue;
    // シーケンス番号: loadFile/onExternalModifyが並走したとき古い結果を捨てる
    this.loadSeq = 0;
    this.externalModifySeq = 0;
    this.currentFile = null;
    this.writeDebounce = new DebounceQueue(debounceMs);
  }
  async loadFile(file) {
    const seq = ++this.loadSeq;
    this.currentFile = file;
    const content = await this.vault.read(file);
    if (seq !== this.loadSeq) return;
    this.setEditorValue(content, false);
  }
  onEditorChange() {
    if (!this.currentFile) return;
    this.writeDebounce.schedule(async () => {
      if (!this.currentFile) return;
      await this.vault.modify(this.currentFile, this.getEditorValue());
    });
  }
  async onExternalModify(file) {
    if (file !== this.currentFile) return;
    const seq = ++this.externalModifySeq;
    const externalContent = await this.vault.read(file);
    if (seq !== this.externalModifySeq || file !== this.currentFile) return;
    if (externalContent === this.getEditorValue()) return;
    this.setEditorValue(externalContent, true);
  }
  onFileDelete(file) {
    if (file !== this.currentFile) return;
    this.currentFile = null;
    this.setEditorValue("", false);
  }
  onFileRename(file, oldPath) {
    if (this.currentFile && this.currentFile.path === oldPath) {
      this.currentFile = file;
    }
  }
  async dispose() {
    await this.writeDebounce.flushAndExecute();
    this.currentFile = null;
  }
};

// src/ui/EditorElement.ts
var KANJI_RE_STR = "[\u4E00-\u9FFF\u3400-\u4DBF\u{20000}-\u{2A6DF}\u3005\u3006\u3024]+";
var EditorElement = class {
  constructor(container) {
    this.el = container.createEl("div");
    this.el.addClass("tate-editor");
    this.el.setAttribute("contenteditable", "true");
    this.el.setAttribute("spellcheck", "false");
    this.el.setAttribute("data-placeholder", "\u30D5\u30A1\u30A4\u30EB\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044");
  }
  getValue() {
    return Array.from(this.el.childNodes).map((n) => this.serializeNode(n)).join("");
  }
  setValue(content, preserveCursor) {
    if (this.getValue() === content) return;
    if (preserveCursor && document.activeElement === this.el) {
      const pos = this.getVisibleOffset();
      this.el.innerHTML = this.parseToHtml(content);
      this.setVisibleOffset(pos);
    } else {
      this.el.innerHTML = this.parseToHtml(content);
    }
  }
  // 》が入力されたときに直前のルビ記法を <ruby> 要素に変換する。
  // input（isComposing=false）および compositionend の後に呼ぶ。
  handleRubyCompletion() {
    var _a, _b, _c;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    const range = sel.getRangeAt(0);
    if (range.startContainer.nodeType !== Node.TEXT_NODE) return;
    if (this.isInsideRuby(range.startContainer)) return;
    const textNode = range.startContainer;
    const textBefore = (_b = (_a = textNode.textContent) == null ? void 0 : _a.slice(0, range.startOffset)) != null ? _b : "";
    if (!textBefore.endsWith("\u300B")) return;
    let match = textBefore.match(/\|([^|《》\n]+)《([^《》\n]*)》$/);
    let explicit = true;
    if (!match) {
      match = textBefore.match(new RegExp(`(${KANJI_RE_STR})\u300A([^\u300A\u300B\\n]*)\u300B$`, "u"));
      explicit = false;
    }
    if (!match) return;
    const fullMatch = match[0];
    const base = match[1];
    const rt = match[2];
    const matchStart = range.startOffset - fullMatch.length;
    const before = textNode.textContent.slice(0, matchStart);
    const after = textNode.textContent.slice(range.startOffset);
    const rubyEl = this.createRubyEl(base, rt, explicit);
    const parent = textNode.parentNode;
    const afterNode = document.createTextNode(after);
    parent.insertBefore(afterNode, (_c = textNode.nextSibling) != null ? _c : null);
    parent.insertBefore(rubyEl, afterNode);
    if (before) {
      textNode.textContent = before;
    } else {
      parent.removeChild(textNode);
    }
    const newRange = document.createRange();
    newRange.setStartAfter(rubyEl);
    newRange.collapse(true);
    sel.removeAllRanges();
    sel.addRange(newRange);
  }
  applySettings(settings) {
    this.el.style.fontFamily = settings.fontFamily;
    this.el.style.fontSize = `${settings.fontSize}px`;
  }
  adjustWidth() {
  }
  focus() {
    this.el.focus();
  }
  // ---- ルビパーサー（Aozora 記法 → innerHTML） ----
  parseToHtml(text) {
    const segments = this.splitByExplicitRuby(text);
    const html = segments.map(
      (seg) => seg.type === "ruby" ? seg.html : this.convertImplicitRuby(seg.text)
    ).join("");
    return html.replace(/\n/g, "<br>");
  }
  splitByExplicitRuby(text) {
    const result = [];
    const re = /\|([^|《》\n]+)《([^《》\n]*)》/g;
    let lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      if (m.index > lastIndex) {
        result.push({ type: "text", text: text.slice(lastIndex, m.index) });
      }
      result.push({
        type: "ruby",
        html: `<ruby data-ruby-explicit="true">${this.esc(m[1])}<rt>${this.esc(m[2])}</rt></ruby>`
      });
      lastIndex = re.lastIndex;
    }
    if (lastIndex < text.length) {
      result.push({ type: "text", text: text.slice(lastIndex) });
    }
    return result;
  }
  convertImplicitRuby(text) {
    const re = new RegExp(`(${KANJI_RE_STR})\u300A([^\u300A\u300B\\n]*)\u300B`, "gu");
    const parts = [];
    let lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      if (m.index > lastIndex) {
        parts.push(this.esc(text.slice(lastIndex, m.index)));
      }
      parts.push(
        `<ruby data-ruby-explicit="false">${this.esc(m[1])}<rt>${this.esc(m[2])}</rt></ruby>`
      );
      lastIndex = re.lastIndex;
    }
    if (lastIndex < text.length) {
      parts.push(this.esc(text.slice(lastIndex)));
    }
    return parts.join("");
  }
  esc(text) {
    return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }
  // ---- DOM シリアライザ（innerHTML → Aozora 記法） ----
  serializeNode(node) {
    var _a, _b, _c, _d;
    if (node.nodeType === Node.TEXT_NODE) {
      return (_a = node.textContent) != null ? _a : "";
    }
    if (!(node instanceof HTMLElement)) return "";
    switch (node.tagName) {
      case "RUBY": {
        const explicit = node.getAttribute("data-ruby-explicit") !== "false";
        const base = Array.from(node.childNodes).filter((n) => !(n instanceof HTMLElement && n.tagName === "RT")).map((n) => this.serializeNode(n)).join("");
        const rt = (_c = (_b = node.querySelector("rt")) == null ? void 0 : _b.textContent) != null ? _c : "";
        return explicit ? `|${base}\u300A${rt}\u300B` : `${base}\u300A${rt}\u300B`;
      }
      case "BR":
        if (node.parentElement !== this.el && ((_d = node.parentElement) == null ? void 0 : _d.tagName) === "DIV" && node === node.parentElement.lastChild) {
          return "";
        }
        return "\n";
      case "DIV": {
        const content = Array.from(node.childNodes).map((n) => this.serializeNode(n)).join("");
        return node.previousSibling !== null ? "\n" + content : content;
      }
      default:
        return Array.from(node.childNodes).map((n) => this.serializeNode(n)).join("");
    }
  }
  // ---- カーソル操作（<rt> 内を除いた visible 文字数でオフセット管理） ----
  getVisibleOffset() {
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return 0;
    const range = sel.getRangeAt(0);
    let count = 0;
    const walker = document.createTreeWalker(this.el, NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      if (node === range.startContainer) {
        if (!this.isInsideRt(node)) count += range.startOffset;
        break;
      }
      if (!this.isInsideRt(node)) count += node.length;
      node = walker.nextNode();
    }
    return count;
  }
  setVisibleOffset(offset) {
    const sel = window.getSelection();
    if (!sel) return;
    let remaining = offset;
    const walker = document.createTreeWalker(this.el, NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      if (!this.isInsideRt(node)) {
        if (remaining <= node.length) {
          const range2 = document.createRange();
          range2.setStart(node, remaining);
          range2.collapse(true);
          sel.removeAllRanges();
          sel.addRange(range2);
          return;
        }
        remaining -= node.length;
      }
      node = walker.nextNode();
    }
    const range = document.createRange();
    range.selectNodeContents(this.el);
    range.collapse(false);
    sel.removeAllRanges();
    sel.addRange(range);
  }
  isInsideRt(node) {
    let parent = node.parentElement;
    while (parent && parent !== this.el) {
      if (parent.tagName === "RT") return true;
      parent = parent.parentElement;
    }
    return false;
  }
  isInsideRuby(node) {
    let parent = node.parentElement;
    while (parent && parent !== this.el) {
      if (parent.tagName === "RUBY") return true;
      parent = parent.parentElement;
    }
    return false;
  }
  createRubyEl(base, rt, explicit) {
    const rubyEl = document.createElement("ruby");
    rubyEl.setAttribute("data-ruby-explicit", String(explicit));
    rubyEl.appendChild(document.createTextNode(base));
    const rtEl = document.createElement("rt");
    rtEl.textContent = rt;
    rubyEl.appendChild(rtEl);
    return rubyEl;
  }
};

// src/view.ts
var TATE_VIEW_TYPE = "tate-vertical-writing";
var VerticalWritingView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.editorEl = null;
    this.syncCoordinator = null;
  }
  getViewType() {
    return TATE_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u7E26\u66F8\u304D";
  }
  getIcon() {
    return "pilcrow";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("tate-container");
    const editorEl = new EditorElement(container);
    this.editorEl = editorEl;
    editorEl.applySettings(this.plugin.settings);
    const syncCoordinator = new SyncCoordinator(
      this.app.vault,
      () => editorEl.getValue(),
      (content, preserveCursor) => editorEl.setValue(content, preserveCursor)
    );
    this.syncCoordinator = syncCoordinator;
    this.registerDomEvent(editorEl.el, "input", (e) => {
      syncCoordinator.onEditorChange();
      if (!e.isComposing) {
        editorEl.handleRubyCompletion();
      }
    });
    this.registerDomEvent(editorEl.el, "compositionend", () => {
      editorEl.handleRubyCompletion();
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile) syncCoordinator.onExternalModify(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian.TFile) syncCoordinator.onFileDelete(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile) syncCoordinator.onFileRename(file, oldPath);
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (!file || file === syncCoordinator.currentFile) return;
        syncCoordinator.loadFile(file);
      })
    );
    await this.loadInitialFile(syncCoordinator);
  }
  async loadInitialFile(syncCoordinator) {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      await syncCoordinator.loadFile(activeFile);
      return;
    }
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      if (leaf.view instanceof import_obsidian.MarkdownView && leaf.view.file) {
        await syncCoordinator.loadFile(leaf.view.file);
        return;
      }
    }
  }
  async onClose() {
    var _a;
    await ((_a = this.syncCoordinator) == null ? void 0 : _a.dispose());
  }
  applySettings(settings) {
    var _a;
    (_a = this.editorEl) == null ? void 0 : _a.applySettings(settings);
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  fontFamily: '"Hiragino Mincho ProN", "Yu Mincho", "YuMincho", "MS Mincho", serif',
  fontSize: 18
};
var TateSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u7E26\u66F8\u304D\u30D3\u30E5\u30FC \u8A2D\u5B9A" });
    new import_obsidian2.Setting(containerEl).setName("\u30D5\u30A9\u30F3\u30C8\u30D5\u30A1\u30DF\u30EA\u30FC").setDesc("\u7E26\u66F8\u304D\u8868\u793A\u306B\u4F7F\u3046\u30D5\u30A9\u30F3\u30C8\uFF08CSS font-family \u5F62\u5F0F\uFF09").addText((text) => text.setPlaceholder('"Hiragino Mincho ProN", serif').setValue(this.plugin.settings.fontFamily).onChange(async (value) => {
      this.plugin.settings.fontFamily = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u30D5\u30A9\u30F3\u30C8\u30B5\u30A4\u30BA (px)").setDesc("\u7E26\u66F8\u304D\u30D3\u30E5\u30FC\u306E\u30D5\u30A9\u30F3\u30C8\u30B5\u30A4\u30BA\uFF08\u30D4\u30AF\u30BB\u30EB\uFF09").addSlider((slider) => slider.setLimits(10, 48, 1).setValue(this.plugin.settings.fontSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.fontSize = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
  }
};

// src/main.ts
var TatePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      TATE_VIEW_TYPE,
      (leaf) => new VerticalWritingView(leaf, this)
    );
    this.addRibbonIcon("pilcrow", "\u7E26\u66F8\u304D\u3067\u958B\u304F", () => this.activateView());
    this.addCommand({
      id: "open-tate-view",
      name: "Open vertical writing view",
      callback: () => this.activateView()
    });
    this.addSettingTab(new TateSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  applySettingsToAllViews() {
    this.app.workspace.getLeavesOfType(TATE_VIEW_TYPE).forEach((leaf) => {
      if (leaf.view instanceof VerticalWritingView) {
        leaf.view.applySettings(this.settings);
      }
    });
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(TATE_VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: TATE_VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
};
