/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TatePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/view.ts
var import_obsidian = require("obsidian");

// src/sync/DebounceQueue.ts
var DebounceQueue = class {
  constructor(delayMs = 500) {
    this.timer = null;
    this.pending = null;
    this.delayMs = delayMs;
  }
  schedule(fn) {
    this.pending = fn;
    if (this.timer !== null) clearTimeout(this.timer);
    this.timer = setTimeout(async () => {
      this.timer = null;
      const f = this.pending;
      this.pending = null;
      if (f) await f();
    }, this.delayMs);
  }
  // ペンディング中のコールバックをキャンセルせず即時実行する（ビューを閉じる際などに使用）
  async flushAndExecute() {
    if (this.timer !== null) {
      clearTimeout(this.timer);
      this.timer = null;
    }
    if (this.pending) {
      const f = this.pending;
      this.pending = null;
      await f();
    }
  }
};

// src/sync/SyncCoordinator.ts
var SyncCoordinator = class {
  constructor(vault, getEditorValue, setEditorValue, debounceMs = 500) {
    this.vault = vault;
    this.getEditorValue = getEditorValue;
    this.setEditorValue = setEditorValue;
    // シーケンス番号: loadFile/onExternalModifyが並走したとき古い結果を捨てる
    this.loadSeq = 0;
    this.externalModifySeq = 0;
    this.currentFile = null;
    this.writeDebounce = new DebounceQueue(debounceMs);
  }
  async loadFile(file) {
    const seq = ++this.loadSeq;
    this.currentFile = file;
    const content = await this.vault.read(file);
    if (seq !== this.loadSeq) return;
    this.setEditorValue(content, false);
  }
  onEditorChange() {
    if (!this.currentFile) return;
    this.writeDebounce.schedule(async () => {
      if (!this.currentFile) return;
      await this.vault.modify(this.currentFile, this.getEditorValue());
    });
  }
  async onExternalModify(file) {
    if (file !== this.currentFile) return;
    const seq = ++this.externalModifySeq;
    const externalContent = await this.vault.read(file);
    if (seq !== this.externalModifySeq || file !== this.currentFile) return;
    if (externalContent === this.getEditorValue()) return;
    this.setEditorValue(externalContent, true);
  }
  onFileDelete(file) {
    if (file !== this.currentFile) return;
    this.currentFile = null;
    this.setEditorValue("", false);
  }
  onFileRename(file, oldPath) {
    if (this.currentFile && this.currentFile.path === oldPath) {
      this.currentFile = file;
    }
  }
  async dispose() {
    await this.writeDebounce.flushAndExecute();
    this.currentFile = null;
  }
};

// src/ui/EditorElement.ts
var KANJI_RE_STR = "[\u4E00-\u9FFF\u3400-\u4DBF\u{20000}-\u{2A6DF}\u3005\u3006\u3024]+";
var EditorElement = class {
  constructor(container) {
    // インライン展開中の編集スパン。null なら展開なし。
    this.expandedEl = null;
    // selectionchange ハンドラ内での DOM 操作中に再入しないためのガード
    this.isModifyingDom = false;
    // expandForEditing 時のシリアライズ済みテキスト（collapseEditing での変化検出用）
    this.expandedElOriginalText = null;
    // コマンド実行時に使う選択範囲キャッシュ（コマンドパレット起動でフォーカスが外れた後も保持）
    this.savedRange = null;
    this.el = container.createEl("div");
    this.el.addClass("tate-editor");
    this.el.setAttribute("contenteditable", "true");
    this.el.setAttribute("spellcheck", "false");
    this.el.setAttribute("data-placeholder", "\u30D5\u30A1\u30A4\u30EB\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044");
  }
  getValue() {
    return Array.from(this.el.childNodes).map((n) => this.serializeNode(n)).join("");
  }
  setValue(content, preserveCursor) {
    this.expandedEl = null;
    this.expandedElOriginalText = null;
    this.savedRange = null;
    if (this.getValue() === content) return;
    if (preserveCursor && document.activeElement === this.el) {
      const pos = this.getVisibleOffset();
      this.el.innerHTML = this.parseToHtml(content);
      this.setVisibleOffset(pos);
    } else {
      this.el.innerHTML = this.parseToHtml(content);
    }
  }
  // ---- インライン展開/収束（selectionchange から呼ぶ） ----
  // カーソル移動のたびに呼ばれ、ruby/tcy 要素を展開・収束する
  handleSelectionChange() {
    if (!this.isModifyingDom) {
      if (!this.expandedEl || !this.expandedEl.isConnected) {
        const actualSpan = this.el.querySelector("span.tate-editing");
        if (actualSpan !== this.expandedEl) {
          this.expandedEl = actualSpan;
          this.expandedElOriginalText = null;
        }
      }
      const sc = window.getSelection();
      if (sc && sc.rangeCount > 0) {
        const rc = sc.getRangeAt(0);
        if (!rc.collapsed && this.el.contains(rc.startContainer) && this.el.contains(rc.endContainer)) {
          this.savedRange = {
            startContainer: rc.startContainer,
            startOffset: rc.startOffset,
            endContainer: rc.endContainer,
            endOffset: rc.endOffset
          };
        }
      }
    }
    if (this.isModifyingDom) return;
    const sel0 = window.getSelection();
    if (!this.expandedEl && (!sel0 || sel0.rangeCount === 0 || !this.el.contains(sel0.getRangeAt(0).startContainer))) return;
    this.isModifyingDom = true;
    try {
      const sel = window.getSelection();
      if (!sel || sel.rangeCount === 0) return;
      const range = sel.getRangeAt(0);
      if (this.expandedEl && this.expandedEl.contains(range.startContainer)) {
        return;
      }
      if (this.expandedEl) {
        const savedNode = range.startContainer;
        const savedOffset = range.startOffset;
        this.collapseEditing();
        this.savedRange = null;
        if (savedNode.isConnected && this.el.contains(savedNode)) {
          try {
            const maxOffset = savedNode.nodeType === Node.TEXT_NODE ? savedNode.length : savedNode.childNodes.length;
            const r = document.createRange();
            r.setStart(savedNode, Math.min(savedOffset, maxOffset));
            r.collapse(true);
            sel.removeAllRanges();
            sel.addRange(r);
          } catch (e) {
          }
        }
      }
      if (sel.rangeCount === 0) return;
      const currentRange = sel.getRangeAt(0);
      if (!this.el.contains(currentRange.startContainer)) return;
      const target = this.findExpandableAncestor(currentRange.startContainer);
      if (target) {
        this.expandForEditing(target, currentRange);
      }
    } finally {
      this.isModifyingDom = false;
    }
  }
  // ---- ルビ・縦中横ライブ変換（input/compositionend から呼ぶ） ----
  // 》が入力されたときに直前のルビ記法を <ruby> 要素に変換する
  handleRubyCompletion() {
    var _a, _b;
    if (this.expandedEl) return;
    if (this.isModifyingDom) return;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    const range = sel.getRangeAt(0);
    if (range.startContainer.nodeType !== Node.TEXT_NODE) return;
    if (this.isInsideRuby(range.startContainer)) return;
    const textNode = range.startContainer;
    const textBefore = (_b = (_a = textNode.textContent) == null ? void 0 : _a.slice(0, range.startOffset)) != null ? _b : "";
    if (!textBefore.endsWith("\u300B")) return;
    let match = textBefore.match(/[|｜]([^|｜《》\n]+)《([^《》\n]*)》$/);
    let explicit = true;
    if (!match) {
      match = textBefore.match(new RegExp(`(${KANJI_RE_STR})\u300A([^\u300A\u300B\\n]*)\u300B$`, "u"));
      explicit = false;
    }
    if (!match) return;
    const base = match[1];
    const rt = match[2];
    const matchStart = range.startOffset - match[0].length;
    this.isModifyingDom = true;
    try {
      const rubyEl = this.createRubyEl(base, rt, explicit);
      rubyEl.setAttribute("data-new-el", "1");
      this.execInsertHtml(textNode, matchStart, range.startOffset, rubyEl.outerHTML);
      const inserted = this.el.querySelector('[data-new-el="1"]');
      if (inserted) {
        inserted.removeAttribute("data-new-el");
        this.el.focus();
        const afterSel = window.getSelection();
        const r = document.createRange();
        r.setStartAfter(inserted);
        r.collapse(true);
        afterSel.removeAllRanges();
        afterSel.addRange(r);
      }
    } finally {
      this.isModifyingDom = false;
    }
  }
  // ］が入力されたときに直前の縦中横記法を <span class="tcy"> 要素に変換する
  handleTcyCompletion() {
    this.handleAnnotationCompletion("\uFF3D", /［＃「([^「」\n]+)」は縦中横］$/, (c) => this.createTcyEl(c));
  }
  // ---- コマンドパレットから呼ぶ選択ラップメソッド ----
  // 選択テキストを tate-editing スパンとして展開し、カーソルを《》の間に置く
  // カーソルがスパン外に出ると collapseEditing() が <ruby> 要素に収束する
  wrapSelectionWithRuby() {
    if (this.expandedEl) return false;
    const r = this.savedRange;
    if (!r || r.startContainer !== r.endContainer || r.startContainer.nodeType !== Node.TEXT_NODE) return false;
    const textNode = r.startContainer;
    const selectedText = textNode.textContent.slice(r.startOffset, r.endOffset);
    if (!selectedText) return false;
    const rawText = `\uFF5C${selectedText}\u300A\u300B`;
    const spanHtml = `<span class="tate-editing" data-ruby-new="1">${this.esc(rawText)}</span>`;
    this.isModifyingDom = true;
    try {
      this.execInsertHtml(textNode, r.startOffset, r.endOffset, spanHtml);
      const span = this.el.querySelector('[data-ruby-new="1"]');
      if (!span) {
        this.el.querySelectorAll("[data-ruby-new]").forEach(
          (el) => el.removeAttribute("data-ruby-new")
        );
        return false;
      }
      span.removeAttribute("data-ruby-new");
      this.expandedEl = span;
      this.expandedElOriginalText = rawText;
      const spanText = span.firstChild;
      if (spanText) {
        this.el.focus();
        const sel = window.getSelection();
        const range = document.createRange();
        range.setStart(spanText, rawText.length - 1);
        range.collapse(true);
        sel.removeAllRanges();
        sel.addRange(range);
      }
    } finally {
      this.isModifyingDom = false;
    }
    this.savedRange = null;
    return true;
  }
  // 選択テキストを縦中横要素に変換する
  wrapSelectionWithTcy() {
    return this.wrapSelectionWith((c) => this.createTcyEl(c));
  }
  // 選択テキストを傍点要素に変換する
  wrapSelectionWithBouten() {
    return this.wrapSelectionWith((c) => this.createBoutenEl(c));
  }
  // ］が入力されたときに直前の傍点記法を <span class="bouten"> 要素に変換する
  handleBoutenCompletion() {
    this.handleAnnotationCompletion("\uFF3D", /［＃「([^「」\n]+)」に傍点］$/, (c) => this.createBoutenEl(c));
  }
  // ---- 選択ラップ・アノテーション完了の共通ロジック ----
  // tcy/bouten など要素置換型ラップの共通実装
  wrapSelectionWith(createElement) {
    if (this.expandedEl) return false;
    const r = this.savedRange;
    if (!r || r.startContainer !== r.endContainer || r.startContainer.nodeType !== Node.TEXT_NODE) return false;
    const textNode = r.startContainer;
    const selectedText = textNode.textContent.slice(r.startOffset, r.endOffset);
    if (!selectedText) return false;
    const newEl = createElement(selectedText);
    newEl.setAttribute("data-wrap-new", "1");
    this.isModifyingDom = true;
    try {
      this.execInsertHtml(textNode, r.startOffset, r.endOffset, newEl.outerHTML);
      const inserted = this.el.querySelector('[data-wrap-new="1"]');
      if (!inserted) {
        this.el.querySelectorAll("[data-wrap-new]").forEach(
          (el) => el.removeAttribute("data-wrap-new")
        );
        return false;
      }
      inserted.removeAttribute("data-wrap-new");
      this.el.focus();
      const sel = window.getSelection();
      const range = document.createRange();
      range.setStartAfter(inserted);
      range.collapse(true);
      sel.removeAllRanges();
      sel.addRange(range);
    } finally {
      this.isModifyingDom = false;
    }
    this.savedRange = null;
    return true;
  }
  // tcy/bouten など終端文字で確定するライブ変換の共通実装
  handleAnnotationCompletion(endChar, re, createElement) {
    var _a, _b;
    if (this.expandedEl) return;
    if (this.isModifyingDom) return;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    const range = sel.getRangeAt(0);
    if (range.startContainer.nodeType !== Node.TEXT_NODE) return;
    if (this.isInsideRuby(range.startContainer)) return;
    const textNode = range.startContainer;
    const textBefore = (_b = (_a = textNode.textContent) == null ? void 0 : _a.slice(0, range.startOffset)) != null ? _b : "";
    if (!textBefore.endsWith(endChar)) return;
    const annotationMatch = textBefore.match(re);
    if (!annotationMatch) return;
    const content = annotationMatch[1];
    const annotationStart = range.startOffset - annotationMatch[0].length;
    if (!textBefore.slice(0, annotationStart).endsWith(content)) return;
    this.isModifyingDom = true;
    try {
      const newEl = createElement(content);
      newEl.setAttribute("data-new-el", "1");
      this.execInsertHtml(textNode, annotationStart - content.length, range.startOffset, newEl.outerHTML);
      const inserted = this.el.querySelector('[data-new-el="1"]');
      if (inserted) {
        inserted.removeAttribute("data-new-el");
        this.el.focus();
        const afterSel = window.getSelection();
        const r = document.createRange();
        r.setStartAfter(inserted);
        r.collapse(true);
        afterSel.removeAllRanges();
        afterSel.addRange(r);
      }
    } finally {
      this.isModifyingDom = false;
    }
  }
  // paste イベントハンドラ: リッチテキストを排除してプレーンテキストのみを挿入する
  handlePaste(e) {
    var _a, _b;
    e.preventDefault();
    const text = (_b = (_a = e.clipboardData) == null ? void 0 : _a.getData("text/plain")) != null ? _b : "";
    if (!text) return;
    document.execCommand("insertText", false, text);
  }
  applySettings(settings) {
    this.el.style.fontFamily = settings.fontFamily;
    this.el.style.fontSize = `${settings.fontSize}px`;
    this.el.toggleClass("tate-auto-indent", settings.autoIndent);
    this.el.style.lineBreak = settings.lineBreak;
  }
  adjustWidth() {
  }
  focus() {
    this.el.focus();
  }
  // ---- インライン展開/収束 プライベートヘルパー ----
  // node の祖先を遡って最初の展開可能要素（ruby/明示tcy）を返す
  findExpandableAncestor(node) {
    let el = node instanceof HTMLElement ? node : node.parentElement;
    while (el && el !== this.el) {
      if (el.tagName === "RUBY") return el;
      if (el.tagName === "SPAN" && el.getAttribute("data-tcy") === "explicit") return el;
      if (el.tagName === "SPAN" && el.getAttribute("data-bouten")) return el;
      el = el.parentElement;
    }
    return null;
  }
  // target を生テキストの編集スパンに展開し、カーソルを対応位置に設定する
  expandForEditing(target, range) {
    const rawText = this.serializeNode(target);
    const cursorOffset = this.rawOffsetForExpand(
      target,
      range.startContainer,
      range.startOffset
    );
    const span = document.createElement("span");
    span.className = "tate-editing";
    span.textContent = rawText;
    target.parentNode.replaceChild(span, target);
    this.expandedEl = span;
    this.expandedElOriginalText = rawText;
    const textNode = span.firstChild;
    if (textNode) {
      const sel = window.getSelection();
      if (sel) {
        const r = document.createRange();
        r.setStart(textNode, Math.min(cursorOffset, textNode.length));
        r.collapse(true);
        sel.removeAllRanges();
        sel.addRange(r);
      }
    }
  }
  // 編集スパンを収束し、内容を再パースして元の位置に挿入する（カーソルは呼び出し元が処理）
  collapseEditing() {
    var _a, _b, _c;
    if (!this.expandedEl) return;
    if (!this.expandedEl.isConnected) {
      this.expandedEl = null;
      this.expandedElOriginalText = null;
      return;
    }
    let rawText = (_a = this.expandedEl.textContent) != null ? _a : "";
    const hasChanged = this.expandedElOriginalText === null || rawText !== this.expandedElOriginalText;
    const parent = this.expandedEl.parentNode;
    const nextSibling = this.expandedEl.nextSibling;
    if (hasChanged) {
      let precedingTextNode = null;
      let precedingChars = "";
      const extraChars = this.getExtraCharsFromAnnotation(rawText);
      if (extraChars.length > 0) {
        const prev = this.expandedEl.previousSibling;
        if (prev && prev.nodeType === Node.TEXT_NODE) {
          const prevText = prev;
          if (((_b = prevText.textContent) != null ? _b : "").endsWith(extraChars)) {
            precedingTextNode = prevText;
            precedingChars = extraChars;
            rawText = precedingChars + rawText;
          }
        }
      }
      this.el.focus();
      const sel = window.getSelection();
      const r = document.createRange();
      if (precedingTextNode) {
        r.setStart(precedingTextNode, precedingTextNode.length - precedingChars.length);
        r.setEndAfter(this.expandedEl);
      } else {
        r.selectNode(this.expandedEl);
      }
      sel.removeAllRanges();
      sel.addRange(r);
      const spanRef = this.expandedEl;
      this.expandedEl = null;
      this.expandedElOriginalText = null;
      const html = this.parseInlineToHtml(rawText, true);
      document.execCommand("insertHTML", false, html);
      if (spanRef.isConnected) {
        const spanParent = spanRef.parentNode;
        const spanNext = spanRef.nextSibling;
        if (precedingTextNode && precedingTextNode.isConnected) {
          precedingTextNode.textContent = ((_c = precedingTextNode.textContent) != null ? _c : "").slice(0, -precedingChars.length);
        }
        spanParent.removeChild(spanRef);
        const tempDiv = document.createElement("div");
        tempDiv.innerHTML = html;
        while (tempDiv.firstChild) {
          spanParent.insertBefore(tempDiv.firstChild, spanNext);
        }
      }
    } else {
      parent.removeChild(this.expandedEl);
      this.expandedEl = null;
      this.expandedElOriginalText = null;
      const tempDiv = document.createElement("div");
      tempDiv.innerHTML = this.parseInlineToHtml(rawText, true);
      while (tempDiv.firstChild) {
        parent.insertBefore(tempDiv.firstChild, nextSibling);
      }
    }
  }
  // 要素内のカーソル位置を raw テキスト上の文字オフセットに変換する
  rawOffsetForExpand(el, node, offset) {
    if (el.tagName === "RUBY") {
      const explicit = el.getAttribute("data-ruby-explicit") !== "false";
      const prefix = explicit ? 1 : 0;
      const baseLen = Array.from(el.childNodes).filter((n) => !(n instanceof HTMLElement && n.tagName === "RT")).reduce((sum, n) => {
        var _a, _b;
        return sum + ((_b = (_a = n.textContent) == null ? void 0 : _a.length) != null ? _b : 0);
      }, 0);
      const rt = el.querySelector("rt");
      if (rt && rt.contains(node)) {
        return prefix + baseLen + 1 + offset;
      } else {
        return prefix + offset;
      }
    } else {
      return offset;
    }
  }
  // ---- パーサー（Aozora 記法 → innerHTML） ----
  // ドキュメント全体用: 各段落を <div> で包む（text-indent を段落ごとに適用するため）
  parseToHtml(text) {
    if (!text) return "";
    return text.split("\n").map((line) => `<div>${this.parseInlineToHtml(line) || "<br>"}</div>`).join("");
  }
  // インライン要素用: <div> で包まずAozora記法をHTML変換する（collapseEditing で使用）
  // lenient=true のとき、前方コンテンツが「」内容と一致しない不正なアノテーションでも
  // 「」内容を使って要素を生成する（インライン編集で「」のみ変更した場合に対応）
  parseInlineToHtml(text, lenient = false) {
    return this.applyParsers(text, [
      (t) => this.splitByExplicitRuby(t),
      (t) => this.splitByExplicitTcy(t, lenient),
      (t) => this.splitByExplicitBouten(t, lenient),
      (t) => this.splitByImplicitRuby(t)
    ]);
  }
  // テキストにパーサーを順番に適用し、HTML 文字列を返す
  applyParsers(text, parsers) {
    let segments = [{ type: "text", text }];
    for (const parser of parsers) {
      segments = segments.flatMap(
        (seg) => seg.type === "text" ? parser(seg.text) : [seg]
      );
    }
    return segments.map((seg) => seg.type === "html" ? seg.html : this.esc(seg.text)).join("");
  }
  // 明示ルビ ｜base《rt》（または |base《rt》）を分割する
  splitByExplicitRuby(text) {
    const result = [];
    const re = /[|｜]([^|｜《》\n]+)《([^《》\n]*)》/g;
    let lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      if (m.index > lastIndex) {
        result.push({ type: "text", text: text.slice(lastIndex, m.index) });
      }
      result.push({
        type: "html",
        html: `<ruby data-ruby-explicit="true">${this.esc(m[1])}<rt>${this.esc(m[2])}</rt></ruby>`
      });
      lastIndex = re.lastIndex;
    }
    if (lastIndex < text.length) {
      result.push({ type: "text", text: text.slice(lastIndex) });
    }
    return result;
  }
  // 明示縦中横 X［＃「X」は縦中横］ を分割する
  splitByExplicitTcy(text, lenient = false) {
    return this.splitByAnnotation(
      text,
      /［＃「([^「」\n]+)」は縦中横］/g,
      (c) => `<span data-tcy="explicit" class="tcy">${this.esc(c)}</span>`,
      lenient
    );
  }
  // 傍点 base［＃「base」に傍点］ を分割する
  splitByExplicitBouten(text, lenient = false) {
    return this.splitByAnnotation(
      text,
      /［＃「([^「」\n]+)」に傍点］/g,
      (c) => `<span data-bouten="sesame" class="bouten">${this.esc(c)}</span>`,
      lenient
    );
  }
  // 前方参照型アノテーション記法「content［＃「content」...］」の共通分割ロジック
  // lenient=true のとき、前方コンテンツが「」内容と一致しない不正アノテーションでも
  // 「」内容で要素を生成する。前方コンテンツのうち content.length 文字分を捨て、
  // それより前のテキストは保持する（インライン編集で「」のみ変更した場合に対応）。
  splitByAnnotation(text, re, buildHtml, lenient = false) {
    const result = [];
    let lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      const content = m[1];
      const annotationStart = m.index;
      if (!text.slice(lastIndex, annotationStart).endsWith(content)) {
        if (!lenient) {
          result.push({ type: "text", text: text.slice(lastIndex, re.lastIndex) });
          lastIndex = re.lastIndex;
          continue;
        }
        const discardStart = Math.max(lastIndex, annotationStart - content.length);
        if (discardStart > lastIndex) {
          result.push({ type: "text", text: text.slice(lastIndex, discardStart) });
        }
        result.push({ type: "html", html: buildHtml(content) });
        lastIndex = re.lastIndex;
        continue;
      }
      const contentStart = annotationStart - content.length;
      if (contentStart > lastIndex) {
        result.push({ type: "text", text: text.slice(lastIndex, contentStart) });
      }
      result.push({ type: "html", html: buildHtml(content) });
      lastIndex = re.lastIndex;
    }
    if (lastIndex < text.length) {
      result.push({ type: "text", text: text.slice(lastIndex) });
    }
    return result;
  }
  // 省略ルビ kanji《rt》 を分割する
  splitByImplicitRuby(text) {
    const re = new RegExp(`(${KANJI_RE_STR})\u300A([^\u300A\u300B\\n]*)\u300B`, "gu");
    const result = [];
    let lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      if (m.index > lastIndex) {
        result.push({ type: "text", text: text.slice(lastIndex, m.index) });
      }
      result.push({
        type: "html",
        html: `<ruby data-ruby-explicit="false">${this.esc(m[1])}<rt>${this.esc(m[2])}</rt></ruby>`
      });
      lastIndex = re.lastIndex;
    }
    if (lastIndex < text.length) {
      result.push({ type: "text", text: text.slice(lastIndex) });
    }
    return result;
  }
  esc(text) {
    return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }
  // ---- DOM シリアライザ（innerHTML → Aozora 記法） ----
  serializeNode(node) {
    var _a, _b, _c, _d, _e, _f;
    if (node.nodeType === Node.TEXT_NODE) {
      return (_a = node.textContent) != null ? _a : "";
    }
    if (!(node instanceof HTMLElement)) return "";
    switch (node.tagName) {
      case "RUBY": {
        const explicit = node.getAttribute("data-ruby-explicit") !== "false";
        const base = Array.from(node.childNodes).filter((n) => !(n instanceof HTMLElement && n.tagName === "RT")).map((n) => this.serializeNode(n)).join("");
        const rt = (_c = (_b = node.querySelector("rt")) == null ? void 0 : _b.textContent) != null ? _c : "";
        return explicit ? `\uFF5C${base}\u300A${rt}\u300B` : `${base}\u300A${rt}\u300B`;
      }
      case "SPAN": {
        const tcy = node.getAttribute("data-tcy");
        if (tcy === "explicit") {
          const content = (_d = node.textContent) != null ? _d : "";
          return `${content}\uFF3B\uFF03\u300C${content}\u300D\u306F\u7E26\u4E2D\u6A2A\uFF3D`;
        }
        if (node.getAttribute("data-bouten")) {
          const content = (_e = node.textContent) != null ? _e : "";
          return `${content}\uFF3B\uFF03\u300C${content}\u300D\u306B\u508D\u70B9\uFF3D`;
        }
        return Array.from(node.childNodes).map((n) => this.serializeNode(n)).join("");
      }
      case "BR":
        if (node.parentElement !== this.el && ((_f = node.parentElement) == null ? void 0 : _f.tagName) === "DIV" && node === node.parentElement.lastChild) {
          return "";
        }
        return "\n";
      case "DIV": {
        const content = Array.from(node.childNodes).map((n) => this.serializeNode(n)).join("");
        return node.previousSibling !== null ? "\n" + content : content;
      }
      default:
        return Array.from(node.childNodes).map((n) => this.serializeNode(n)).join("");
    }
  }
  // ---- カーソル操作（<rt> 内を除いた visible 文字数でオフセット管理） ----
  getVisibleOffset() {
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return 0;
    const range = sel.getRangeAt(0);
    let count = 0;
    const walker = document.createTreeWalker(this.el, NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      if (node === range.startContainer) {
        if (!this.isInsideRt(node)) count += range.startOffset;
        break;
      }
      if (!this.isInsideRt(node)) count += node.length;
      node = walker.nextNode();
    }
    return count;
  }
  setVisibleOffset(offset) {
    const sel = window.getSelection();
    if (!sel) return;
    let remaining = offset;
    const walker = document.createTreeWalker(this.el, NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      if (!this.isInsideRt(node)) {
        if (remaining <= node.length) {
          const range2 = document.createRange();
          range2.setStart(node, remaining);
          range2.collapse(true);
          sel.removeAllRanges();
          sel.addRange(range2);
          return;
        }
        remaining -= node.length;
      }
      node = walker.nextNode();
    }
    const range = document.createRange();
    range.selectNodeContents(this.el);
    range.collapse(false);
    sel.removeAllRanges();
    sel.addRange(range);
  }
  isInsideRt(node) {
    let parent = node.parentElement;
    while (parent && parent !== this.el) {
      if (parent.tagName === "RT") return true;
      parent = parent.parentElement;
    }
    return false;
  }
  isInsideRuby(node) {
    let parent = node.parentElement;
    while (parent && parent !== this.el) {
      if (parent.tagName === "RUBY") return true;
      parent = parent.parentElement;
    }
    return false;
  }
  // テキストノードの [matchStart, matchEnd) を html で置き換える
  // execCommand('insertHTML') を使うことでブラウザの Undo スタックに記録される
  execInsertHtml(textNode, matchStart, matchEnd, html) {
    const sel = window.getSelection();
    const r = document.createRange();
    r.setStart(textNode, matchStart);
    r.setEnd(textNode, matchEnd);
    sel.removeAllRanges();
    sel.addRange(r);
    document.execCommand("insertHTML", false, html);
  }
  // インライン編集後の収束時に、アノテーション「」内容がスパン内の前方テキストより
  // 長い場合に直前テキストノードから取り込むべき文字列を返す。
  // 例: rawText = '30[#「130」縦中横]' → '1' を返す（content.length=3 > leadingLen=2 → 差分=1文字）
  // 一致する場合（正常アノテーション）は '' を返す。
  getExtraCharsFromAnnotation(rawText) {
    const patterns = [
      /［＃「([^「」\n]+)」は縦中横］/,
      /［＃「([^「」\n]+)」に傍点］/
    ];
    for (const re of patterns) {
      const m = rawText.match(re);
      if (!m || m.index === void 0) continue;
      const content = m[1];
      const leadingText = rawText.slice(0, m.index);
      if (!leadingText.endsWith(content) && content.length > leadingText.length) {
        const extraCount = content.length - leadingText.length;
        return content.slice(0, extraCount);
      }
    }
    return "";
  }
  createRubyEl(base, rt, explicit) {
    const rubyEl = document.createElement("ruby");
    rubyEl.setAttribute("data-ruby-explicit", String(explicit));
    rubyEl.appendChild(document.createTextNode(base));
    const rtEl = document.createElement("rt");
    rtEl.textContent = rt;
    rubyEl.appendChild(rtEl);
    return rubyEl;
  }
  createTcyEl(content) {
    const span = document.createElement("span");
    span.setAttribute("data-tcy", "explicit");
    span.className = "tcy";
    span.textContent = content;
    return span;
  }
  createBoutenEl(content) {
    const span = document.createElement("span");
    span.setAttribute("data-bouten", "sesame");
    span.className = "bouten";
    span.textContent = content;
    return span;
  }
};

// src/view.ts
var TATE_VIEW_TYPE = "tate-vertical-writing";
var VerticalWritingView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.editorEl = null;
    this.syncCoordinator = null;
  }
  getViewType() {
    return TATE_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u7E26\u66F8\u304D";
  }
  getIcon() {
    return "pilcrow";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("tate-container");
    const editorEl = new EditorElement(container);
    this.editorEl = editorEl;
    editorEl.applySettings(this.plugin.settings);
    const syncCoordinator = new SyncCoordinator(
      this.app.vault,
      () => editorEl.getValue(),
      (content, preserveCursor) => editorEl.setValue(content, preserveCursor)
    );
    this.syncCoordinator = syncCoordinator;
    this.registerDomEvent(editorEl.el, "paste", (e) => {
      editorEl.handlePaste(e);
      syncCoordinator.onEditorChange();
    });
    this.registerDomEvent(editorEl.el, "input", (e) => {
      syncCoordinator.onEditorChange();
      if (!e.isComposing) {
        editorEl.handleRubyCompletion();
        editorEl.handleTcyCompletion();
        editorEl.handleBoutenCompletion();
      }
    });
    this.registerDomEvent(editorEl.el, "compositionend", () => {
      editorEl.handleRubyCompletion();
      editorEl.handleTcyCompletion();
      editorEl.handleBoutenCompletion();
    });
    this.registerDomEvent(document, "selectionchange", () => {
      editorEl.handleSelectionChange();
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile) syncCoordinator.onExternalModify(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian.TFile) syncCoordinator.onFileDelete(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile) syncCoordinator.onFileRename(file, oldPath);
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (!file || file === syncCoordinator.currentFile) return;
        syncCoordinator.loadFile(file);
      })
    );
    await this.loadInitialFile(syncCoordinator);
  }
  async loadInitialFile(syncCoordinator) {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      await syncCoordinator.loadFile(activeFile);
      return;
    }
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      if (leaf.view instanceof import_obsidian.MarkdownView && leaf.view.file) {
        await syncCoordinator.loadFile(leaf.view.file);
        return;
      }
    }
  }
  async onClose() {
    var _a;
    await ((_a = this.syncCoordinator) == null ? void 0 : _a.dispose());
  }
  applySettings(settings) {
    var _a;
    (_a = this.editorEl) == null ? void 0 : _a.applySettings(settings);
  }
  applyRuby() {
    this.applyAnnotation((el) => el.wrapSelectionWithRuby());
  }
  applyTcy() {
    this.applyAnnotation((el) => el.wrapSelectionWithTcy());
  }
  applyBouten() {
    this.applyAnnotation((el) => el.wrapSelectionWithBouten());
  }
  applyAnnotation(wrap) {
    var _a;
    if (!this.editorEl) return;
    if (!wrap(this.editorEl)) {
      new import_obsidian.Notice("\u30C6\u30AD\u30B9\u30C8\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044");
    } else {
      (_a = this.syncCoordinator) == null ? void 0 : _a.onEditorChange();
    }
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  fontFamily: '"Hiragino Mincho ProN", "Yu Mincho", "YuMincho", "MS Mincho", serif',
  fontSize: 18,
  autoIndent: true,
  lineBreak: "normal"
};
var TateSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u7E26\u66F8\u304D\u30D3\u30E5\u30FC \u8A2D\u5B9A" });
    new import_obsidian2.Setting(containerEl).setName("\u30D5\u30A9\u30F3\u30C8\u30D5\u30A1\u30DF\u30EA\u30FC").setDesc("\u7E26\u66F8\u304D\u8868\u793A\u306B\u4F7F\u3046\u30D5\u30A9\u30F3\u30C8\uFF08CSS font-family \u5F62\u5F0F\uFF09").addText((text) => text.setPlaceholder('"Hiragino Mincho ProN", serif').setValue(this.plugin.settings.fontFamily).onChange(async (value) => {
      this.plugin.settings.fontFamily = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u30D5\u30A9\u30F3\u30C8\u30B5\u30A4\u30BA (px)").setDesc("\u7E26\u66F8\u304D\u30D3\u30E5\u30FC\u306E\u30D5\u30A9\u30F3\u30C8\u30B5\u30A4\u30BA\uFF08\u30D4\u30AF\u30BB\u30EB\uFF09").addSlider((slider) => slider.setLimits(10, 48, 1).setValue(this.plugin.settings.fontSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.fontSize = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u81EA\u52D5\u5B57\u4E0B\u3052").setDesc("\u5404\u6BB5\u843D\u306E\u884C\u982D\u30921\u6587\u5B57\u5206\u30A4\u30F3\u30C7\u30F3\u30C8\u3059\u308B").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoIndent).onChange(async (value) => {
      this.plugin.settings.autoIndent = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u7981\u5247\u51E6\u7406").setDesc("\u884C\u982D\u30FB\u884C\u672B\u306B\u7F6E\u3051\u306A\u3044\u6587\u5B57\u306E\u30EB\u30FC\u30EB\u30BB\u30C3\u30C8\uFF08CSS line-break \u30D7\u30ED\u30D1\u30C6\u30A3\uFF09").addDropdown((dropdown) => dropdown.addOption("normal", "Normal   \u2014 \u4E00\u822C\u7684\u306A\u7981\u5247\u30EB\u30FC\u30EB").addOption("strict", "Strict   \u2014 \u6700\u3082\u53B3\u683C\uFF08\u5C0F\u66F8\u304D\u4EEE\u540D\u3082\u884C\u982D\u4E0D\u53EF\uFF09").addOption("loose", "Loose    \u2014 \u65B0\u805E\u30B9\u30BF\u30A4\u30EB\uFF08\u6539\u884C\u3092\u512A\u5148\uFF09").addOption("anywhere", "Anywhere \u2014 \u7981\u5247\u306A\u3057\uFF08\u3069\u3053\u3067\u3082\u6539\u884C\uFF09").setValue(this.plugin.settings.lineBreak).onChange(async (value) => {
      this.plugin.settings.lineBreak = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
  }
};

// src/main.ts
var TatePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      TATE_VIEW_TYPE,
      (leaf) => new VerticalWritingView(leaf, this)
    );
    this.addRibbonIcon("pilcrow", "\u7E26\u66F8\u304D\u3067\u958B\u304F", () => this.activateView());
    this.addCommand({
      id: "open-tate-view",
      name: "Open vertical writing view",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "add-ruby",
      name: "Ruby: \u9078\u629E\u30C6\u30AD\u30B9\u30C8\u306B\u30EB\u30D3\u3092\u8A2D\u5B9A",
      callback: () => this.dispatchToView((v) => v.applyRuby())
    });
    this.addCommand({
      id: "add-tcy",
      name: "TCY: \u9078\u629E\u30C6\u30AD\u30B9\u30C8\u3092\u7E26\u4E2D\u6A2A\u306B\u3059\u308B",
      callback: () => this.dispatchToView((v) => v.applyTcy())
    });
    this.addCommand({
      id: "add-bouten",
      name: "BT: \u9078\u629E\u30C6\u30AD\u30B9\u30C8\u306B\u508D\u70B9\u3092\u4ED8\u3051\u308B",
      callback: () => this.dispatchToView((v) => v.applyBouten())
    });
    this.addSettingTab(new TateSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  applySettingsToAllViews() {
    this.app.workspace.getLeavesOfType(TATE_VIEW_TYPE).forEach((leaf) => {
      if (leaf.view instanceof VerticalWritingView) {
        leaf.view.applySettings(this.settings);
      }
    });
  }
  dispatchToView(action) {
    const leaves = this.app.workspace.getLeavesOfType(TATE_VIEW_TYPE);
    if (leaves.length === 0) {
      new import_obsidian3.Notice("\u7E26\u66F8\u304D\u30D3\u30E5\u30FC\u304C\u958B\u3044\u3066\u3044\u307E\u305B\u3093");
      return;
    }
    action(leaves[0].view);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(TATE_VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: TATE_VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
};
