/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TatePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/view.ts
var import_obsidian4 = require("obsidian");

// src/sync/SyncCoordinator.ts
var SyncCoordinator = class {
  constructor(vault, getEditorValue, setEditorValue) {
    this.vault = vault;
    this.getEditorValue = getEditorValue;
    this.setEditorValue = setEditorValue;
    // Sequence numbers: discard stale results when loadFile/onExternalModify run concurrently
    this.loadSeq = 0;
    this.externalModifySeq = 0;
    this.currentFile = null;
  }
  async loadFile(file) {
    const seq = ++this.loadSeq;
    this.currentFile = file;
    const content = await this.vault.read(file);
    if (seq !== this.loadSeq) return;
    this.setEditorValue(content, false);
  }
  async onExternalModify(file) {
    if (file !== this.currentFile) return;
    const seq = ++this.externalModifySeq;
    const externalContent = await this.vault.read(file);
    if (seq !== this.externalModifySeq || file !== this.currentFile) return;
    if (externalContent === this.getEditorValue()) return;
    this.setEditorValue(externalContent, true);
  }
  onFileDelete(file) {
    if (file !== this.currentFile) return;
    this.currentFile = null;
    this.setEditorValue("", false);
  }
  clearCurrentFile() {
    this.currentFile = null;
  }
  onFileRename(file, oldPath) {
    if (this.currentFile && this.currentFile.path === oldPath) {
      this.currentFile = file;
    }
  }
  dispose() {
    this.currentFile = null;
  }
};

// src/ui/EditorElement.ts
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  fontFamily: '"Hiragino Mincho ProN", "Yu Mincho", "YuMincho", "MS Mincho", serif',
  fontSize: 18,
  lineBreak: "normal",
  convertHalfWidthSpace: true,
  autoIndentOnInput: true,
  matchPrecedingIndent: true,
  removeBracketIndent: true,
  expandRubyInline: true,
  expandTcyInline: true,
  expandBoutenInline: true
};
var TateSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u30D5\u30A9\u30F3\u30C8").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u30D5\u30A9\u30F3\u30C8\u30D5\u30A1\u30DF\u30EA\u30FC").setDesc("\u7E26\u66F8\u304D\u8868\u793A\u306B\u4F7F\u3046\u30D5\u30A9\u30F3\u30C8\uFF08CSS font-family \u5F62\u5F0F\uFF09").addText((text) => text.setPlaceholder('"Hiragino Mincho ProN", serif').setValue(this.plugin.settings.fontFamily).onChange(async (value) => {
      this.plugin.settings.fontFamily = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian.Setting(containerEl).setName("\u30D5\u30A9\u30F3\u30C8\u30B5\u30A4\u30BA (px)").setDesc("\u7E26\u66F8\u304D\u30D3\u30E5\u30FC\u306E\u30D5\u30A9\u30F3\u30C8\u30B5\u30A4\u30BA\uFF08\u30D4\u30AF\u30BB\u30EB\uFF09").addSlider((slider) => slider.setLimits(10, 48, 1).setValue(this.plugin.settings.fontSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.fontSize = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5B57\u4E0B\u3052").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u5165\u529B\u3055\u308C\u305F\u534A\u89D2\u30B9\u30DA\u30FC\u30B9\u3092\u5168\u89D2\u30B9\u30DA\u30FC\u30B9\u306B\u5909\u63DB").setDesc("\u30B9\u30DA\u30FC\u30B9\u30AD\u30FC\u3067\u5165\u529B\u3057\u305F\u534A\u89D2\u30B9\u30DA\u30FC\u30B9\u3092\u5168\u89D2\u30B9\u30DA\u30FC\u30B9\uFF08\u3000\uFF09\u306B\u5909\u63DB\u3059\u308B").addToggle((toggle) => toggle.setValue(this.plugin.settings.convertHalfWidthSpace).onChange(async (value) => {
      this.plugin.settings.convertHalfWidthSpace = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian.Setting(containerEl).setName("\u884C\u982D\u306B\u6587\u5B57\u3092\u5165\u529B\u3059\u308B\u3068\u81EA\u52D5\u3067\u5B57\u4E0B\u3052").setDesc("\u884C\u982D\u306B\u30AB\u30FC\u30BD\u30EB\u304C\u3042\u308B\u72B6\u614B\u3067\u6587\u5B57\u3092\u5165\u529B\u3059\u308B\u3068\u3001\u4E00\u6587\u5B57\u5206\u306E\u5168\u89D2\u30B9\u30DA\u30FC\u30B9\u3092\u81EA\u52D5\u633F\u5165\u3059\u308B").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoIndentOnInput).onChange(async (value) => {
      this.plugin.settings.autoIndentOnInput = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5B57\u4E0B\u3052\u3092\u524D\u306E\u884C\u306B\u63C3\u3048\u308B").setDesc("\u524D\u306E\u6BB5\u843D\u306E\u5148\u982D\u5168\u89D2\u30B9\u30DA\u30FC\u30B9\u6570\u306B\u5408\u308F\u305B\u308B").addToggle((toggle) => toggle.setValue(this.plugin.settings.matchPrecedingIndent).onChange(async (value) => {
      this.plugin.settings.matchPrecedingIndent = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian.Setting(containerEl).setName("\u884C\u982D\u306B\u958B\u304D\u30AB\u30AE\u62EC\u5F27\u304C\u5165\u529B\u3055\u308C\u305F\u5834\u5408\u306B\u5B57\u4E0B\u3052\u3092\u81EA\u52D5\u524A\u9664").setDesc("\u884C\u982D\u306E\u5168\u89D2\u30B9\u30DA\u30FC\u30B9\u306E\u5F8C\u308D\u306B\u5168\u89D2\u958B\u304D\u62EC\u5F27\u3092\u5165\u529B\u3057\u305F\u3068\u304D\u3001\u884C\u982D\u306E\u5168\u89D2\u30B9\u30DA\u30FC\u30B9\u30921\u6587\u5B57\u524A\u9664\u3059\u308B").addToggle((toggle) => toggle.setValue(this.plugin.settings.removeBracketIndent).onChange(async (value) => {
      this.plugin.settings.removeBracketIndent = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian.Setting(containerEl).setName("\u7981\u5247\u51E6\u7406").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u7981\u5247\u51E6\u7406").setDesc("\u884C\u982D\u30FB\u884C\u672B\u306B\u7F6E\u3051\u306A\u3044\u6587\u5B57\u306E\u30EB\u30FC\u30EB\u30BB\u30C3\u30C8\uFF08CSS line-break \u30D7\u30ED\u30D1\u30C6\u30A3\uFF09").addDropdown((dropdown) => dropdown.addOption("normal", "Normal   \u2014 \u4E00\u822C\u7684\u306A\u7981\u5247\u30EB\u30FC\u30EB").addOption("strict", "Strict   \u2014 \u6700\u3082\u53B3\u683C\uFF08\u5C0F\u66F8\u304D\u4EEE\u540D\u3082\u884C\u982D\u4E0D\u53EF\uFF09").addOption("loose", "Loose    \u2014 \u65B0\u805E\u30B9\u30BF\u30A4\u30EB\uFF08\u6539\u884C\u3092\u512A\u5148\uFF09").addOption("anywhere", "Anywhere \u2014 \u7981\u5247\u306A\u3057\uFF08\u3069\u3053\u3067\u3082\u6539\u884C\uFF09").setValue(this.plugin.settings.lineBreak).onChange(async (value) => {
      this.plugin.settings.lineBreak = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian.Setting(containerEl).setName("Experimental settings").setHeading();
    containerEl.createEl("p", {
      text: "\u30C7\u30D5\u30A9\u30EB\u30C8\u5024\u4EE5\u5916\u306B\u8A2D\u5B9A\u3059\u308B\u5834\u5408\u3001\u30AB\u30FC\u30BD\u30EB\u79FB\u52D5\u306E\u6319\u52D5\u304C\u4E0D\u5B89\u5B9A\u306B\u306A\u308B\u5834\u5408\u304C\u3042\u308A\u307E\u3059\u3002",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("\u30EB\u30D3\u3092\u30A4\u30F3\u30E9\u30A4\u30F3\u5C55\u958B\u3059\u308B").setDesc("\u30AB\u30FC\u30BD\u30EB\u304C\u30EB\u30D3\u4E0A\u306B\u79FB\u52D5\u3057\u305F\u3068\u304D\u3001\u9752\u7A7A\u8A18\u6CD5\u30C6\u30AD\u30B9\u30C8\u306B\u5C55\u958B\u3057\u3066\u7DE8\u96C6\u3067\u304D\u308B\u3088\u3046\u306B\u3059\u308B (default on)").addToggle((toggle) => toggle.setValue(this.plugin.settings.expandRubyInline).onChange(async (value) => {
      this.plugin.settings.expandRubyInline = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian.Setting(containerEl).setName("\u7E26\u4E2D\u6A2A\u3092\u30A4\u30F3\u30E9\u30A4\u30F3\u5C55\u958B\u3059\u308B").setDesc("\u30AB\u30FC\u30BD\u30EB\u304C\u7E26\u4E2D\u6A2A\u4E0A\u306B\u79FB\u52D5\u3057\u305F\u3068\u304D\u3001\u9752\u7A7A\u8A18\u6CD5\u30C6\u30AD\u30B9\u30C8\u306B\u5C55\u958B\u3057\u3066\u7DE8\u96C6\u3067\u304D\u308B\u3088\u3046\u306B\u3059\u308B (default on)").addToggle((toggle) => toggle.setValue(this.plugin.settings.expandTcyInline).onChange(async (value) => {
      this.plugin.settings.expandTcyInline = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
    new import_obsidian.Setting(containerEl).setName("\u508D\u70B9\u3092\u30A4\u30F3\u30E9\u30A4\u30F3\u5C55\u958B\u3059\u308B").setDesc("\u30AB\u30FC\u30BD\u30EB\u304C\u508D\u70B9\u4E0A\u306B\u79FB\u52D5\u3057\u305F\u3068\u304D\u3001\u9752\u7A7A\u8A18\u6CD5\u30C6\u30AD\u30B9\u30C8\u306B\u5C55\u958B\u3057\u3066\u7DE8\u96C6\u3067\u304D\u308B\u3088\u3046\u306B\u3059\u308B (default on)").addToggle((toggle) => toggle.setValue(this.plugin.settings.expandBoutenInline).onChange(async (value) => {
      this.plugin.settings.expandBoutenInline = value;
      await this.plugin.saveSettings();
      this.plugin.applySettingsToAllViews();
    }));
  }
};

// src/ui/SegmentMap.ts
var KANJI_RE_STR = "[\u4E00-\u9FFF\u3400-\u4DBF\u{20000}-\u{2A6DF}\u3005\u3006\u3024]+";
function buildSegmentMap(source) {
  const tokens = tokenize(source);
  const segments = [];
  let srcPos = 0;
  let viewPos = 0;
  for (const tok of tokens) {
    const seg = {
      kind: tok.kind,
      srcStart: srcPos,
      srcLen: tok.srcLen,
      viewStart: viewPos,
      viewLen: tok.viewLen
    };
    if (tok.baseLen !== void 0) seg.baseLen = tok.baseLen;
    if (tok.rtLen !== void 0) seg.rtLen = tok.rtLen;
    segments.push(seg);
    srcPos += tok.srcLen;
    viewPos += tok.viewLen;
  }
  return segments;
}
function srcToView(segs, srcOffset) {
  for (const seg of segs) {
    if (srcOffset < seg.srcStart) break;
    if (srcOffset < seg.srcStart + seg.srcLen) {
      return mapSrcLocalToView(seg, srcOffset - seg.srcStart);
    }
  }
  if (segs.length === 0) return 0;
  const last = segs[segs.length - 1];
  return last.viewStart + last.viewLen;
}
function viewToSrc(segs, viewOffset) {
  for (const seg of segs) {
    if (seg.viewLen === 0) continue;
    if (viewOffset < seg.viewStart + seg.viewLen) {
      const local = Math.max(0, viewOffset - seg.viewStart);
      return mapViewLocalToSrc(seg, local);
    }
  }
  if (segs.length === 0) return 0;
  const last = segs[segs.length - 1];
  return last.srcStart + last.srcLen;
}
function mapSrcLocalToView(seg, local) {
  var _a, _b;
  switch (seg.kind) {
    case "plain":
    case "newline":
      return seg.viewStart + local;
    case "ruby-explicit": {
      const baseLen = (_a = seg.baseLen) != null ? _a : seg.viewLen;
      if (local === 0) return seg.viewStart;
      if (local <= baseLen) return seg.viewStart + local - 1;
      return seg.viewStart + seg.viewLen;
    }
    case "ruby-implicit": {
      const baseLen = (_b = seg.baseLen) != null ? _b : seg.viewLen;
      if (local <= baseLen) return seg.viewStart + local;
      return seg.viewStart + seg.viewLen;
    }
    case "tcy":
    case "bouten": {
      if (local <= seg.viewLen) return seg.viewStart + local;
      return seg.viewStart + seg.viewLen;
    }
  }
}
function mapViewLocalToSrc(seg, local) {
  switch (seg.kind) {
    case "plain":
    case "newline":
      return seg.srcStart + local;
    case "ruby-explicit":
      return seg.srcStart + 1 + local;
    case "ruby-implicit":
    case "tcy":
    case "bouten":
      return seg.srcStart + local;
  }
}
function tokenize(source) {
  let items = [{ resolved: false, raw: source }];
  const tcyRe = /［＃「([^「」\n]+)」は縦中横］/g;
  const boutenRe = /［＃「([^「」\n]+)」に傍点］/g;
  items = flatScan(items, scanExplicitRuby);
  items = flatScan(items, (raw) => scanAnnotation(raw, tcyRe, "tcy", 9));
  items = flatScan(items, (raw) => scanAnnotation(raw, boutenRe, "bouten", 8));
  items = flatScan(items, scanImplicitRuby);
  items = flatScan(items, scanNewlines);
  return items.map((item) => {
    if (!item.resolved) {
      const len = item.raw.length;
      return { resolved: true, kind: "plain", srcLen: len, viewLen: len };
    }
    return item;
  });
}
function flatScan(items, scanner) {
  return items.flatMap((item) => item.resolved ? [item] : scanner(item.raw));
}
function scanExplicitRuby(raw) {
  const re = /[|｜]([^|｜《》\n]+)《([^《》\n]*)》/g;
  const result = [];
  let lastIndex = 0;
  let m;
  while ((m = re.exec(raw)) !== null) {
    if (m.index > lastIndex) {
      result.push({ resolved: false, raw: raw.slice(lastIndex, m.index) });
    }
    const baseLen = m[1].length;
    const rtLen = m[2].length;
    result.push({
      resolved: true,
      kind: "ruby-explicit",
      srcLen: baseLen + rtLen + 3,
      // ｜ + base + 《 + rt + 》
      viewLen: baseLen,
      baseLen,
      rtLen
    });
    lastIndex = re.lastIndex;
  }
  if (lastIndex < raw.length) result.push({ resolved: false, raw: raw.slice(lastIndex) });
  return result;
}
function scanAnnotation(raw, re, kind, bracketFixedLen) {
  re.lastIndex = 0;
  const result = [];
  let lastIndex = 0;
  let m;
  while ((m = re.exec(raw)) !== null) {
    const content = m[1];
    const annotationStart = m.index;
    if (!raw.slice(lastIndex, annotationStart).endsWith(content)) {
      result.push({ resolved: false, raw: raw.slice(lastIndex, re.lastIndex) });
      lastIndex = re.lastIndex;
      continue;
    }
    const contentStart = annotationStart - content.length;
    if (contentStart > lastIndex) {
      result.push({ resolved: false, raw: raw.slice(lastIndex, contentStart) });
    }
    result.push({
      resolved: true,
      kind,
      srcLen: content.length * 2 + bracketFixedLen,
      // content + ［＃「content」...］
      viewLen: content.length
    });
    lastIndex = re.lastIndex;
  }
  if (lastIndex < raw.length) result.push({ resolved: false, raw: raw.slice(lastIndex) });
  return result;
}
function scanImplicitRuby(raw) {
  const re = new RegExp(`(${KANJI_RE_STR})\u300A([^\u300A\u300B\\n]*)\u300B`, "gu");
  const result = [];
  let lastIndex = 0;
  let m;
  while ((m = re.exec(raw)) !== null) {
    if (m.index > lastIndex) {
      result.push({ resolved: false, raw: raw.slice(lastIndex, m.index) });
    }
    const baseLen = m[1].length;
    const rtLen = m[2].length;
    result.push({
      resolved: true,
      kind: "ruby-implicit",
      srcLen: baseLen + rtLen + 2,
      // base + 《 + rt + 》
      viewLen: baseLen,
      baseLen,
      rtLen
    });
    lastIndex = re.lastIndex;
  }
  if (lastIndex < raw.length) result.push({ resolved: false, raw: raw.slice(lastIndex) });
  return result;
}
function scanNewlines(raw) {
  const parts = raw.split("\n");
  const result = [];
  for (let i = 0; i < parts.length; i++) {
    if (parts[i].length > 0) result.push({ resolved: false, raw: parts[i] });
    if (i < parts.length - 1) {
      result.push({ resolved: true, kind: "newline", srcLen: 1, viewLen: 0 });
    }
  }
  return result;
}

// src/ui/AozoraParser.ts
var KANJI_RE_STR2 = "[\u4E00-\u9FFF\u3400-\u4DBF\u{20000}-\u{2A6DF}\u3005\u3006\u3024]+";
function parseToHtml(text) {
  if (!text) return "<div><br></div>";
  return text.split("\n").map((line) => `<div>${parseInlineToHtml(line) || "<br>"}</div>`).join("");
}
function parseInlineToHtml(text) {
  return applyParsers(text, [
    splitByExplicitRuby,
    splitByExplicitTcy,
    splitByExplicitBouten,
    splitByImplicitRuby
  ]);
}
function applyParsers(text, parsers) {
  let segments = [{ type: "text", text }];
  for (const parser of parsers) {
    segments = segments.flatMap(
      (seg) => seg.type === "text" ? parser(seg.text) : [seg]
    );
  }
  return segments.map((seg) => seg.type === "html" ? seg.html : esc(seg.text)).join("");
}
function splitByExplicitRuby(text) {
  const result = [];
  const re = /[|｜]([^|｜《》\n]+)《([^《》\n]*)》/g;
  let lastIndex = 0;
  let m;
  while ((m = re.exec(text)) !== null) {
    if (m.index > lastIndex) {
      result.push({ type: "text", text: text.slice(lastIndex, m.index) });
    }
    result.push({
      type: "html",
      html: `<ruby data-ruby-explicit="true">${esc(m[1])}<rt>${esc(m[2])}</rt></ruby>`
    });
    lastIndex = re.lastIndex;
  }
  if (lastIndex < text.length) {
    result.push({ type: "text", text: text.slice(lastIndex) });
  }
  return result;
}
function splitByExplicitTcy(text) {
  return splitByAnnotation(
    text,
    /［＃「([^「」\n]+)」は縦中横］/g,
    (c) => `<span data-tcy="explicit" class="tcy">${esc(c)}</span>`
  );
}
function splitByExplicitBouten(text) {
  return splitByAnnotation(
    text,
    /［＃「([^「」\n]+)」に傍点］/g,
    (c) => `<span data-bouten="sesame" class="bouten">${esc(c)}</span>`
  );
}
function splitByAnnotation(text, re, buildHtml) {
  const result = [];
  let lastIndex = 0;
  let m;
  while ((m = re.exec(text)) !== null) {
    const content = m[1];
    const annotationStart = m.index;
    if (!text.slice(lastIndex, annotationStart).endsWith(content)) {
      result.push({ type: "text", text: text.slice(lastIndex, re.lastIndex) });
      lastIndex = re.lastIndex;
      continue;
    }
    const contentStart = annotationStart - content.length;
    if (contentStart > lastIndex) {
      result.push({ type: "text", text: text.slice(lastIndex, contentStart) });
    }
    result.push({ type: "html", html: buildHtml(content) });
    lastIndex = re.lastIndex;
  }
  if (lastIndex < text.length) {
    result.push({ type: "text", text: text.slice(lastIndex) });
  }
  return result;
}
function splitByImplicitRuby(text) {
  const re = new RegExp(`(${KANJI_RE_STR2})\u300A([^\u300A\u300B\\n]*)\u300B`, "gu");
  const result = [];
  let lastIndex = 0;
  let m;
  while ((m = re.exec(text)) !== null) {
    if (m.index > lastIndex) {
      result.push({ type: "text", text: text.slice(lastIndex, m.index) });
    }
    result.push({
      type: "html",
      html: `<ruby data-ruby-explicit="false">${esc(m[1])}<rt>${esc(m[2])}</rt></ruby>`
    });
    lastIndex = re.lastIndex;
  }
  if (lastIndex < text.length) {
    result.push({ type: "text", text: text.slice(lastIndex) });
  }
  return result;
}
function esc(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function serializeNode(node, rootEl) {
  var _a, _b, _c, _d, _e, _f, _g;
  if (node.nodeType === Node.TEXT_NODE) {
    return (_a = node.textContent) != null ? _a : "";
  }
  if (!(node instanceof HTMLElement)) return "";
  switch (node.tagName) {
    case "RUBY": {
      const explicit = node.getAttribute("data-ruby-explicit") !== "false";
      const base = Array.from(node.childNodes).filter((n) => !(n instanceof HTMLElement && n.tagName === "RT")).map((n) => serializeNode(n, rootEl)).join("");
      const rt = (_c = (_b = node.querySelector("rt")) == null ? void 0 : _b.textContent) != null ? _c : "";
      return explicit ? `\uFF5C${base}\u300A${rt}\u300B` : `${base}\u300A${rt}\u300B`;
    }
    case "SPAN": {
      const tcy = node.getAttribute("data-tcy");
      if (tcy === "explicit") {
        const content = (_d = node.textContent) != null ? _d : "";
        return `${content}\uFF3B\uFF03\u300C${content}\u300D\u306F\u7E26\u4E2D\u6A2A\uFF3D`;
      }
      if (node.getAttribute("data-bouten")) {
        const content = (_e = node.textContent) != null ? _e : "";
        return `${content}\uFF3B\uFF03\u300C${content}\u300D\u306B\u508D\u70B9\uFF3D`;
      }
      if (node.classList.contains("tate-cursor-anchor")) {
        return ((_f = node.textContent) != null ? _f : "").replace(/\u200B/g, "");
      }
      return Array.from(node.childNodes).map((n) => serializeNode(n, rootEl)).join("");
    }
    case "BR":
      if (node.parentElement !== rootEl && ((_g = node.parentElement) == null ? void 0 : _g.tagName) === "DIV" && node === node.parentElement.lastChild) {
        return "";
      }
      return "\n";
    case "DIV": {
      const content = Array.from(node.childNodes).map((n) => serializeNode(n, rootEl)).join("");
      return node.previousSibling !== null ? "\n" + content : content;
    }
    default:
      return Array.from(node.childNodes).map((n) => serializeNode(n, rootEl)).join("");
  }
}

// src/ui/domHelpers.ts
function createRubyEl(base, rt, explicit) {
  const rubyEl = document.createElement("ruby");
  rubyEl.setAttribute("data-ruby-explicit", String(explicit));
  rubyEl.appendChild(document.createTextNode(base));
  const rtEl = document.createElement("rt");
  rtEl.textContent = rt;
  rubyEl.appendChild(rtEl);
  return rubyEl;
}
function createTcyEl(content) {
  const span = document.createElement("span");
  span.setAttribute("data-tcy", "explicit");
  span.className = "tcy";
  span.textContent = content;
  return span;
}
function createBoutenEl(content) {
  const span = document.createElement("span");
  span.setAttribute("data-bouten", "sesame");
  span.className = "bouten";
  span.textContent = content;
  return span;
}
function createCursorAnchor() {
  const anchor = document.createElement("span");
  anchor.className = "tate-cursor-anchor";
  anchor.appendChild(document.createTextNode("\u200B"));
  return anchor;
}
function insertAnnotationElement(textNode, matchStart, matchEnd, element) {
  const parentEl = textNode.parentNode;
  const precedingText = textNode.data.slice(0, matchStart);
  const followingText = textNode.data.slice(matchEnd);
  const next = textNode.nextSibling;
  parentEl.removeChild(textNode);
  if (precedingText) parentEl.insertBefore(document.createTextNode(precedingText), next);
  parentEl.insertBefore(element, next);
  if (followingText) parentEl.insertBefore(document.createTextNode(followingText), next);
  return element;
}
function setCursorAfter(node) {
  const sel = window.getSelection();
  if (!sel) return;
  const r = document.createRange();
  r.setStartAfter(node);
  r.collapse(true);
  sel.removeAllRanges();
  sel.addRange(r);
}
function findAncestor(node, pred, rootEl) {
  let el = node instanceof HTMLElement ? node : node.parentElement;
  while (el && el !== rootEl) {
    if (pred(el)) return el;
    el = el.parentElement;
  }
  return null;
}
function findBoutenAncestor(node, rootEl) {
  return findAncestor(node, (el) => !!el.getAttribute("data-bouten"), rootEl);
}
function findTcyAncestor(node, rootEl) {
  return findAncestor(node, (el) => el.classList.contains("tcy"), rootEl);
}
function isInsideRuby(node, rootEl) {
  return findAncestor(node, (el) => el.tagName === "RUBY", rootEl) !== null;
}
function findCursorAnchorAncestor(node, rootEl) {
  return findAncestor(node, (el) => el.classList.contains("tate-cursor-anchor"), rootEl);
}
function isInsideRtNode(node, rootEl) {
  var _a;
  return findAncestor((_a = node.parentElement) != null ? _a : node, (el) => el.tagName === "RT", rootEl) !== null;
}
function findLastBaseTextInElement(el, rootEl) {
  const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT);
  let lastText = null;
  let node = walker.nextNode();
  while (node) {
    if (!isInsideRtNode(node, rootEl)) lastText = node;
    node = walker.nextNode();
  }
  if (!lastText) return null;
  return { node: lastText, offset: lastText.length };
}
function rawOffsetForExpand(el, node, offset) {
  if (el.tagName === "RUBY") {
    const explicit = el.getAttribute("data-ruby-explicit") !== "false";
    const prefix = explicit ? 1 : 0;
    const baseLen = Array.from(el.childNodes).filter((n) => !(n instanceof HTMLElement && n.tagName === "RT")).reduce((sum, n) => {
      var _a, _b;
      return sum + ((_b = (_a = n.textContent) == null ? void 0 : _a.length) != null ? _b : 0);
    }, 0);
    const rt = el.querySelector("rt");
    if (rt && rt.contains(node)) {
      return prefix + baseLen + 1 + offset;
    } else {
      return prefix + offset;
    }
  } else {
    return offset;
  }
}
function getExtraCharsFromAnnotation(rawText) {
  const patterns = [
    /［＃「([^「」\n]+)」は縦中横］/,
    /［＃「([^「」\n]+)」に傍点］/
  ];
  for (const re of patterns) {
    const m = rawText.match(re);
    if (!m || m.index === void 0) continue;
    const content = m[1];
    const leadingText = rawText.slice(0, m.index);
    if (!leadingText.endsWith(content) && content.length > leadingText.length) {
      const extraCount = content.length - leadingText.length;
      return content.slice(0, extraCount);
    }
  }
  return "";
}

// src/ui/BoutenGuard.ts
var BoutenGuard = class {
  constructor(el) {
    this.el = el;
    this.boutenJustCollapsed = null;
  }
  clear() {
    this.boutenJustCollapsed = null;
  }
  set(bouten, originalText) {
    this.boutenJustCollapsed = { el: bouten, originalText };
  }
  get() {
    return this.boutenJustCollapsed;
  }
  // Returns the bouten span that should intercept the next insertText event due to Chrome's
  // post-collapse cursor behavior, or null if not applicable.
  // Covers three cursor positions that occur after collapse:
  //   1. cursor normalized into bouten itself (Chrome moves it back synchronously)
  //   2. cursor redirected into the adjacent anchor span (end-of-line)
  //   3. cursor redirected to the start of the next text node (mid-line)
  // Non-collapsed selections (e.g. Ctrl+A) are excluded to avoid false positives.
  getCursorBoutenSpan(expandBouten, expandedEl) {
    if (!this.boutenJustCollapsed || !expandBouten || expandedEl) return null;
    const bouten = this.boutenJustCollapsed.el;
    if (!bouten.isConnected) {
      this.boutenJustCollapsed = null;
      return null;
    }
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0 || !sel.getRangeAt(0).collapsed) return null;
    const range = sel.getRangeAt(0);
    const container = range.startContainer;
    if (findBoutenAncestor(container, this.el) === bouten) return bouten;
    const nextSib = bouten.nextSibling;
    if (nextSib) {
      if (nextSib === container || nextSib instanceof HTMLElement && nextSib.contains(container)) {
        return bouten;
      }
      if (container.nodeType === Node.ELEMENT_NODE && container.childNodes[range.startOffset] === nextSib) {
        return bouten;
      }
    }
    return null;
  }
  // Inserts chars into the DOM immediately after bouten without going through the Selection API.
  // End-of-line (anchor span follows): creates a new text node between bouten and anchor.
  // Mid-line (text node follows): prepends to that text node.
  // Moves the cursor to just after the inserted text.
  insertAfterBouten(bouten, chars) {
    var _a;
    const next = bouten.nextSibling;
    let targetNode;
    let targetOffset;
    if (next instanceof HTMLElement && next.classList.contains("tate-cursor-anchor") && ((_a = next.firstChild) == null ? void 0 : _a.nodeType) === Node.TEXT_NODE) {
      const textNode = document.createTextNode(chars);
      bouten.parentNode.insertBefore(textNode, next);
      targetNode = textNode;
      targetOffset = chars.length;
    } else if ((next == null ? void 0 : next.nodeType) === Node.TEXT_NODE) {
      const textNode = next;
      textNode.insertData(0, chars);
      targetNode = textNode;
      targetOffset = chars.length;
    } else {
      const textNode = document.createTextNode(chars);
      bouten.parentNode.insertBefore(textNode, next != null ? next : null);
      targetNode = textNode;
      targetOffset = chars.length;
    }
    const sel = window.getSelection();
    if (sel) {
      const r = document.createRange();
      r.setStart(targetNode, targetOffset);
      r.collapse(true);
      sel.removeAllRanges();
      sel.addRange(r);
    }
    this.boutenJustCollapsed = null;
  }
  // Called in compositionend (before commitToCm6) to move IME text that landed inside a
  // post-collapse bouten span out to after the span. Returns true if the DOM was changed.
  handleBoutenPostCollapseInput() {
    var _a;
    if (!this.boutenJustCollapsed) return false;
    const { el: bouten, originalText } = this.boutenJustCollapsed;
    if (!bouten.isConnected) {
      this.boutenJustCollapsed = null;
      return false;
    }
    const currentText = (_a = bouten.textContent) != null ? _a : "";
    if (currentText === originalText) return false;
    if (!currentText.startsWith(originalText)) {
      this.boutenJustCollapsed = null;
      return false;
    }
    const extraChars = currentText.slice(originalText.length);
    bouten.textContent = originalText;
    this.insertAfterBouten(bouten, extraChars);
    return true;
  }
  // Redirects cursor to a stable position after the bouten span to prevent re-expansion.
  // Called when Chrome normalizes the cursor from the adjacent anchor back into bouten.
  // End-of-line: redirects to end of anchor text (after U+200B), which the anchor span handler
  // intercepts on the next selectionchange so expansion does not fire.
  // Mid-line: redirects to the start of the following text node, a true text-level stable position.
  redirectCursorOutOfCollapsedBouten(bouten, sel) {
    var _a;
    const next = bouten.nextSibling;
    const r = document.createRange();
    if (next instanceof HTMLElement && next.classList.contains("tate-cursor-anchor") && ((_a = next.firstChild) == null ? void 0 : _a.nodeType) === Node.TEXT_NODE) {
      const anchorText = next.firstChild;
      r.setStart(anchorText, anchorText.length);
    } else if ((next == null ? void 0 : next.nodeType) === Node.TEXT_NODE) {
      r.setStart(next, 0);
    } else if (next) {
      r.setStartBefore(next);
    } else {
      r.setStartAfter(bouten);
    }
    r.collapse(true);
    sel.removeAllRanges();
    sel.addRange(r);
  }
};

// src/ui/CursorAnchorManager.ts
var CursorAnchorManager = class {
  constructor(el) {
    this.el = el;
    this.pendingAnchorSkip = null;
  }
  // Sets the skip direction based on the navigation key that was just pressed.
  setSkipDirection(key) {
    if (key === "ArrowDown") this.pendingAnchorSkip = "forward";
    else if (key === "ArrowUp") this.pendingAnchorSkip = "backward";
    else this.pendingAnchorSkip = null;
  }
  // If the placed anchor is at end-of-line, clears the pending skip so the cursor rests there.
  // If content follows, the skip is kept and fires on the next selectionchange.
  clearSkipIfEndOfLine(placedAnchor) {
    var _a;
    const nextAfterAnchor = placedAnchor.nextSibling;
    const atEndOfLine = !nextAfterAnchor || nextAfterAnchor instanceof HTMLElement && nextAfterAnchor.tagName === "BR" && nextAfterAnchor === ((_a = nextAfterAnchor.parentElement) == null ? void 0 : _a.lastChild);
    if (atEndOfLine) this.pendingAnchorSkip = null;
  }
  // Handles the anchor-skip logic inside handleSelectionChange.
  // Consumes the pending skip direction and moves the cursor past the anchor if applicable.
  // Returns true if the cursor is inside an anchor span (caller must not proceed to expansion).
  handleAnchorPosition(currentRange, sel) {
    var _a;
    const anchorSpan = findCursorAnchorAncestor(currentRange.startContainer, this.el);
    const savedSkip = this.pendingAnchorSkip;
    this.pendingAnchorSkip = null;
    if (!anchorSpan) return false;
    const text = (_a = anchorSpan.textContent) != null ? _a : "";
    if ((text === "\u200B" || text === "") && savedSkip !== null) {
      try {
        const r = document.createRange();
        if (savedSkip === "forward") {
          const pos = this.findPositionAfterAnchor(anchorSpan);
          if (pos) r.setStart(pos.node, pos.offset);
          else r.setStartAfter(anchorSpan);
        } else {
          const pos = this.findPositionBeforeAnchor(anchorSpan);
          if (pos) r.setStart(pos.node, pos.offset);
          else r.setStartAfter(anchorSpan);
        }
        r.collapse(true);
        sel.removeAllRanges();
        sel.addRange(r);
      } catch (e) {
      }
    }
    return true;
  }
  // Places the cursor just after a collapsed annotation element.
  // Inserts a cursor-anchor span at end-of-line if needed and adjusts pendingAnchorSkip.
  // Caller is responsible for the boutenGuard.set() call that follows.
  placeCursorAfterCollapse(nextSib, parentEl, sel) {
    var _a;
    try {
      const r = document.createRange();
      let placedAnchor = null;
      if (nextSib && nextSib.isConnected) {
        if (nextSib instanceof HTMLElement && nextSib.classList.contains("tate-cursor-anchor") && ((_a = nextSib.firstChild) == null ? void 0 : _a.nodeType) === Node.TEXT_NODE) {
          r.setStart(nextSib.firstChild, 0);
          placedAnchor = nextSib;
        } else {
          r.setStartBefore(nextSib);
        }
      } else {
        const anchor = createCursorAnchor();
        parentEl.appendChild(anchor);
        r.setStart(anchor.firstChild, 0);
        placedAnchor = anchor;
      }
      r.collapse(true);
      sel.removeAllRanges();
      sel.addRange(r);
      if (placedAnchor) this.clearSkipIfEndOfLine(placedAnchor);
    } catch (e) {
    }
  }
  // Inserts a cursor anchor after el if el is at end-of-line and has no anchor yet.
  // Must be called before expandForEditing so that the anchor survives as nextSibling
  // of the tate-editing span and is available when the user exits past the closing bracket.
  ensureCursorAnchorAfter(el) {
    var _a;
    const next = el.nextSibling;
    if (next instanceof HTMLElement && next.classList.contains("tate-cursor-anchor")) return;
    const isEndOfLine = !next || next instanceof HTMLElement && next.tagName === "BR" && next === ((_a = next.parentElement) == null ? void 0 : _a.lastChild);
    if (!isEndOfLine) return;
    const anchor = createCursorAnchor();
    el.parentNode.insertBefore(anchor, next);
  }
  // Called after input/compositionend when cursor may be inside a tate-cursor-anchor span.
  // Removes U+200B once real characters have been typed, or re-inserts it when the span is empty.
  // Caller is responsible for setting/clearing the isModifyingDom guard around this call.
  handleCursorAnchorInput() {
    var _a;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    const range = sel.getRangeAt(0);
    const anchor = findCursorAnchorAncestor(range.startContainer, this.el);
    if (!anchor) return;
    const text = (_a = anchor.textContent) != null ? _a : "";
    if (text === "") {
      const zws = document.createTextNode("\u200B");
      anchor.replaceChildren(zws);
      const r = document.createRange();
      r.setStart(zws, 0);
      r.collapse(true);
      sel.removeAllRanges();
      sel.addRange(r);
    } else if (text !== "\u200B" && text.includes("\u200B")) {
      const cleaned = text.replace(/\u200B/g, "");
      const textNode = anchor.firstChild;
      if ((textNode == null ? void 0 : textNode.nodeType) === Node.TEXT_NODE) {
        const prevOffset = range.startContainer === textNode ? range.startOffset : cleaned.length;
        textNode.textContent = cleaned;
        const adjustedOffset = text.slice(0, prevOffset).replace(/\u200B/g, "").length;
        const r = document.createRange();
        r.setStart(textNode, Math.min(adjustedOffset, cleaned.length));
        r.collapse(true);
        sel.removeAllRanges();
        sel.addRange(r);
      }
    }
  }
  // Returns the first non-<rt> text position after the anchor.
  // Checks siblings within the same paragraph first; falls back to the next paragraph.
  findPositionAfterAnchor(anchor) {
    let sibling = anchor.nextSibling;
    while (sibling) {
      if (sibling.nodeType === Node.TEXT_NODE) {
        const t = sibling;
        if (!isInsideRtNode(t, this.el)) return { node: t, offset: 0 };
      } else if (sibling.nodeType === Node.ELEMENT_NODE) {
        const walker = document.createTreeWalker(sibling, NodeFilter.SHOW_TEXT);
        let node = walker.nextNode();
        while (node) {
          if (!isInsideRtNode(node, this.el)) return { node, offset: 0 };
          node = walker.nextNode();
        }
      }
      sibling = sibling.nextSibling;
    }
    const parentDiv = anchor.parentElement;
    if (!parentDiv) return null;
    let next = parentDiv.nextSibling;
    while (next) {
      const walker = document.createTreeWalker(next, NodeFilter.SHOW_TEXT);
      let node = walker.nextNode();
      while (node) {
        if (!isInsideRtNode(node, this.el)) return { node, offset: 0 };
        node = walker.nextNode();
      }
      next = next.nextSibling;
    }
    return null;
  }
  // Returns the last non-<rt> text position before the anchor on the same line.
  // Descends into element siblings (e.g. <ruby>) to find their last base text node,
  // which causes selectionchange to trigger expandForEditing on the ruby.
  // Falls back to the last text of the previous paragraph if nothing is found on the same line.
  findPositionBeforeAnchor(anchor) {
    let prev = anchor.previousSibling;
    while (prev) {
      if (prev.nodeType === Node.TEXT_NODE) {
        return { node: prev, offset: prev.length };
      }
      if (prev.nodeType === Node.ELEMENT_NODE) {
        const pos = findLastBaseTextInElement(prev, this.el);
        if (pos) return pos;
      }
      prev = prev.previousSibling;
    }
    const parentDiv = anchor.parentElement;
    if (!parentDiv) return null;
    let prevDiv = parentDiv.previousSibling;
    while (prevDiv) {
      const walker = document.createTreeWalker(prevDiv, NodeFilter.SHOW_TEXT);
      let lastText = null;
      let node = walker.nextNode();
      while (node) {
        if (!isInsideRtNode(node, this.el)) lastText = node;
        node = walker.nextNode();
      }
      if (lastText) return { node: lastText, offset: lastText.length };
      prevDiv = prevDiv.previousSibling;
    }
    return null;
  }
};

// src/ui/LiveConverter.ts
var LiveConverter = class {
  constructor(el) {
    this.el = el;
  }
  // Converts a ruby notation just before the cursor to a <ruby> element when 》 is typed.
  // If rt is empty, creates a tate-editing span and returns it via result.newExpanded.
  // Caller must check expandedEl and isModifyingDom before calling, and apply result.newExpanded.
  handleRubyCompletion() {
    var _a, _b;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return { converted: false };
    const range = sel.getRangeAt(0);
    if (range.startContainer.nodeType !== Node.TEXT_NODE) return { converted: false };
    if (isInsideRuby(range.startContainer, this.el)) return { converted: false };
    const textNode = range.startContainer;
    const textBefore = (_b = (_a = textNode.textContent) == null ? void 0 : _a.slice(0, range.startOffset)) != null ? _b : "";
    if (!textBefore.endsWith("\u300B")) return { converted: false };
    let match = textBefore.match(/[|｜]([^|｜《》\n]+)《([^《》\n]*)》$/);
    let explicit = true;
    if (!match) {
      match = textBefore.match(new RegExp(`(${KANJI_RE_STR2})\u300A([^\u300A\u300B\\n]*)\u300B$`, "u"));
      explicit = false;
    }
    if (!match) return { converted: false };
    const base = match[1];
    const rt = match[2];
    const matchStart = range.startOffset - match[0].length;
    if (rt === "") {
      const rawText = explicit ? `\uFF5C${base}\u300A\u300B` : `${base}\u300A\u300B`;
      const span = document.createElement("span");
      span.className = "tate-editing";
      span.textContent = rawText;
      insertAnnotationElement(textNode, matchStart, range.startOffset, span);
      const spanText = span.firstChild;
      if (spanText) {
        const r = document.createRange();
        r.setStart(spanText, rawText.length - 1);
        r.collapse(true);
        const s = window.getSelection();
        s.removeAllRanges();
        s.addRange(r);
      }
      return { converted: true, newExpanded: { el: span, originalText: rawText } };
    }
    const rubyEl = createRubyEl(base, rt, explicit);
    const inserted = insertAnnotationElement(textNode, matchStart, range.startOffset, rubyEl);
    setCursorAfter(inserted);
    return { converted: true };
  }
  // Converts a tate-chu-yoko notation just before the cursor to a <span class="tcy"> when ］ is typed.
  // Returns true if a conversion occurred.
  handleTcyCompletion() {
    return this.handleAnnotationCompletion("\uFF3D", /［＃「([^「」\n]+)」は縦中横］$/, createTcyEl);
  }
  // Converts a bouten notation just before the cursor to a <span class="bouten"> when ］ is typed.
  // Returns true if a conversion occurred.
  handleBoutenCompletion() {
    return this.handleAnnotationCompletion("\uFF3D", /［＃「([^「」\n]+)」に傍点］$/, createBoutenEl);
  }
  // Shared implementation for live conversions that complete on a terminal character (tcy, bouten).
  handleAnnotationCompletion(endChar, re, createElement) {
    var _a, _b;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return false;
    const range = sel.getRangeAt(0);
    if (range.startContainer.nodeType !== Node.TEXT_NODE) return false;
    if (isInsideRuby(range.startContainer, this.el)) return false;
    const textNode = range.startContainer;
    const textBefore = (_b = (_a = textNode.textContent) == null ? void 0 : _a.slice(0, range.startOffset)) != null ? _b : "";
    if (!textBefore.endsWith(endChar)) return false;
    const annotationMatch = textBefore.match(re);
    if (!annotationMatch) return false;
    const content = annotationMatch[1];
    const annotationStart = range.startOffset - annotationMatch[0].length;
    if (!textBefore.slice(0, annotationStart).endsWith(content)) return false;
    const newEl = createElement(content);
    const inserted = insertAnnotationElement(
      textNode,
      annotationStart - content.length,
      range.startOffset,
      newEl
    );
    setCursorAfter(inserted);
    return true;
  }
};

// src/ui/InlineExpander.ts
var import_obsidian2 = require("obsidian");
var InlineExpander = class {
  constructor(el) {
    this.el = el;
  }
  // Returns the first ancestor of node that is an expandable annotation element,
  // filtered by the caller-provided expand flags.
  findExpandableAncestor(node, ruby, tcy, bouten) {
    let el = node instanceof HTMLElement ? node : node.parentElement;
    while (el && el !== this.el) {
      if (el.tagName === "RUBY" && ruby) return el;
      if (el.tagName === "SPAN" && el.getAttribute("data-tcy") === "explicit" && tcy) return el;
      if (el.tagName === "SPAN" && el.getAttribute("data-bouten") && bouten) return el;
      el = el.parentElement;
    }
    return null;
  }
  // Replaces target with a tate-editing span and positions the cursor.
  // Returns the created span and its raw text (for InlineEditor to store as expandedEl/originalText).
  // Caller is responsible for setting isModifyingDom and clearing inBurst.
  expandForEditing(target, range) {
    const rawText = serializeNode(target, this.el);
    const cursorOffset = rawOffsetForExpand(target, range.startContainer, range.startOffset);
    const span = document.createElement("span");
    span.className = "tate-editing";
    span.textContent = rawText;
    target.parentNode.replaceChild(span, target);
    const textNode = span.firstChild;
    if (textNode) {
      const sel = window.getSelection();
      if (sel) {
        const r = document.createRange();
        r.setStart(textNode, Math.min(cursorOffset, textNode.length));
        r.collapse(true);
        sel.removeAllRanges();
        sel.addRange(r);
      }
    }
    return { el: span, originalText: rawText };
  }
  // Collapses the editing span, re-parses its content, and inserts the result in place.
  // Cursor placement after collapse is handled by the caller.
  // Returns hasChanged (whether content differs from when expansion started) and detached
  // (true when the span was already removed from the DOM — caller must NOT clear inBurst).
  collapseEditing(expandedEl, expandedElOriginalText) {
    var _a, _b, _c;
    if (!expandedEl.isConnected) return { hasChanged: false, detached: true };
    let rawText = (_a = expandedEl.textContent) != null ? _a : "";
    const hasChanged = expandedElOriginalText === null || rawText !== expandedElOriginalText;
    const parent = expandedEl.parentNode;
    const nextSibling = expandedEl.nextSibling;
    let precedingTextNode = null;
    let precedingChars = "";
    if (hasChanged) {
      const extraChars = getExtraCharsFromAnnotation(rawText);
      if (extraChars.length > 0) {
        const prev = expandedEl.previousSibling;
        if ((prev == null ? void 0 : prev.nodeType) === Node.TEXT_NODE) {
          const prevText = prev;
          if (((_b = prevText.textContent) != null ? _b : "").endsWith(extraChars)) {
            precedingTextNode = prevText;
            precedingChars = extraChars;
            rawText = precedingChars + rawText;
          }
        }
      }
    }
    const html = parseInlineToHtml(rawText);
    if (precedingTextNode == null ? void 0 : precedingTextNode.isConnected) {
      precedingTextNode.textContent = ((_c = precedingTextNode.textContent) != null ? _c : "").slice(0, -precedingChars.length);
    }
    parent.removeChild(expandedEl);
    const fragment = (0, import_obsidian2.sanitizeHTMLToDom)(html);
    while (fragment.firstChild) {
      parent.insertBefore(fragment.firstChild, nextSibling);
    }
    return { hasChanged, detached: false };
  }
};

// src/ui/InlineEditor.ts
var InlineEditor = class {
  constructor(el) {
    this.el = el;
    // The editing span currently expanded inline. null if not expanded.
    this.expandedEl = null;
    // Guard to prevent re-entry during DOM manipulation inside the selectionchange handler
    this.isModifyingDom = false;
    // Serialized text captured at expandForEditing time (used to detect changes in collapseEditing)
    this.expandedElOriginalText = null;
    // Cached selection range for command execution (retained even after focus leaves due to command palette)
    this.savedRange = null;
    // Flag indicating there are uncommitted changes pending for CM6.
    // Set by onBeforeInput, cleared by resetBurst() when commitToCm6() completes.
    this.inBurst = false;
    // Per-element-type flags controlling whether cursor entry triggers inline expansion.
    this.expandRuby = true;
    this.expandTcy = true;
    this.expandBouten = true;
    this.boutenGuard = new BoutenGuard(el);
    this.anchorManager = new CursorAnchorManager(el);
    this.liveConverter = new LiveConverter(el);
    this.expander = new InlineExpander(el);
  }
  setExpandSettings(ruby, tcy, bouten) {
    this.expandRuby = ruby;
    this.expandTcy = tcy;
    this.expandBouten = bouten;
  }
  // Resets expansion state, selection cache, and burst flag (called from setValue / applyFromCm6)
  reset() {
    this.expandedEl = null;
    this.expandedElOriginalText = null;
    this.savedRange = null;
    this.inBurst = false;
    this.boutenGuard.clear();
  }
  isExpanded() {
    return this.expandedEl !== null;
  }
  // ---- Inline expand/collapse (call from selectionchange) ----
  // Called on every cursor movement to expand or collapse ruby/tcy elements.
  // Returns true if collapse changed the content (signal for view.ts to call commitToCm6).
  handleSelectionChange() {
    if (!this.isModifyingDom) {
      if (!this.expandedEl || !this.expandedEl.isConnected) {
        const actualSpan = this.el.querySelector("span.tate-editing");
        if (actualSpan !== this.expandedEl) {
          this.expandedEl = actualSpan;
          this.expandedElOriginalText = null;
        }
      }
      const sc = window.getSelection();
      if (sc && sc.rangeCount > 0) {
        const rc = sc.getRangeAt(0);
        if (!rc.collapsed && this.el.contains(rc.startContainer) && this.el.contains(rc.endContainer)) {
          this.savedRange = {
            startContainer: rc.startContainer,
            startOffset: rc.startOffset,
            endContainer: rc.endContainer,
            endOffset: rc.endOffset
          };
        }
      }
    }
    if (this.isModifyingDom) return false;
    const sel0 = window.getSelection();
    if (!this.expandedEl && (!sel0 || sel0.rangeCount === 0 || !this.el.contains(sel0.getRangeAt(0).startContainer))) return false;
    let contentChanged = false;
    this.isModifyingDom = true;
    try {
      const sel = window.getSelection();
      if (!sel || sel.rangeCount === 0) return false;
      const range = sel.getRangeAt(0);
      if (this.expandedEl && this.expandedEl.contains(range.startContainer)) {
        const spanText = this.expandedEl.firstChild;
        const atSpanEnd = spanText && range.startContainer === spanText && range.startOffset >= spanText.length;
        if (!atSpanEnd) return false;
        const nextSib = this.expandedEl.nextSibling;
        const parentEl = this.expandedEl.parentElement;
        contentChanged = this.collapseEditing();
        this.savedRange = null;
        if (parentEl) this.placeCursorAfterCollapse(nextSib, parentEl, sel);
        return contentChanged;
      }
      if (this.expandedEl) {
        const savedNode = range.startContainer;
        const savedOffset = range.startOffset;
        contentChanged = this.collapseEditing();
        this.savedRange = null;
        if (savedNode.isConnected && this.el.contains(savedNode)) {
          try {
            const maxOffset = savedNode.nodeType === Node.TEXT_NODE ? savedNode.length : savedNode.childNodes.length;
            const r = document.createRange();
            r.setStart(savedNode, Math.min(savedOffset, maxOffset));
            r.collapse(true);
            sel.removeAllRanges();
            sel.addRange(r);
          } catch (e) {
          }
        }
      }
      if (sel.rangeCount === 0) return contentChanged;
      const currentRange = sel.getRangeAt(0);
      if (!this.el.contains(currentRange.startContainer)) return contentChanged;
      if (this.anchorManager.handleAnchorPosition(currentRange, sel)) {
        return contentChanged;
      }
      const target = this.findExpandableAncestor(currentRange.startContainer);
      if (target) {
        const bjc = this.boutenGuard.get();
        if (bjc && target === bjc.el) {
          this.boutenGuard.redirectCursorOutOfCollapsedBouten(target, sel);
          return contentChanged;
        }
        this.boutenGuard.clear();
        if (target.tagName === "RUBY" || target.getAttribute("data-tcy") === "explicit" || target.getAttribute("data-bouten"))
          this.anchorManager.ensureCursorAnchorAfter(target);
        this.expandForEditing(target, currentRange);
      }
    } finally {
      this.isModifyingDom = false;
    }
    return contentChanged;
  }
  // ---- Ruby / tcy live conversion (call from input/compositionend) ----
  // Converts a ruby notation just before the cursor to a <ruby> element when 》 is typed.
  // Returns true if a conversion occurred (signal for view.ts to call commitToCm6).
  handleRubyCompletion() {
    if (this.expandedEl || this.isModifyingDom) return false;
    this.isModifyingDom = true;
    try {
      const r = this.liveConverter.handleRubyCompletion();
      if (r.converted && r.newExpanded) {
        this.expandedEl = r.newExpanded.el;
        this.expandedElOriginalText = r.newExpanded.originalText;
      }
      return r.converted;
    } finally {
      this.isModifyingDom = false;
    }
  }
  // Converts a tate-chu-yoko notation just before the cursor to a <span class="tcy"> when ］ is typed.
  // Returns true if a conversion occurred.
  handleTcyCompletion() {
    if (this.expandedEl || this.isModifyingDom) return false;
    this.isModifyingDom = true;
    try {
      return this.liveConverter.handleTcyCompletion();
    } finally {
      this.isModifyingDom = false;
    }
  }
  // Converts a bouten notation just before the cursor to a <span class="bouten"> when ］ is typed.
  // Returns true if a conversion occurred.
  handleBoutenCompletion() {
    if (this.expandedEl || this.isModifyingDom) return false;
    this.isModifyingDom = true;
    try {
      return this.liveConverter.handleBoutenCompletion();
    } finally {
      this.isModifyingDom = false;
    }
  }
  // ---- Selection wrap methods called from the command palette ----
  // Wraps the selected text in a tate-editing span and places the cursor between 《 and 》
  // When the cursor leaves the span, collapseEditing() collapses it to a <ruby> element
  wrapSelectionWithRuby() {
    if (this.expandedEl) return false;
    const resolved = this.resolveSelectionRange();
    if (!resolved) return false;
    const { textNode, startOffset, endOffset } = resolved;
    const selectedText = textNode.data.slice(startOffset, endOffset);
    if (!selectedText) return false;
    const rawText = `\uFF5C${selectedText}\u300A\u300B`;
    const span = document.createElement("span");
    span.className = "tate-editing";
    span.textContent = rawText;
    const parentEl = textNode.parentNode;
    this.isModifyingDom = true;
    try {
      const precedingText = textNode.data.slice(0, startOffset);
      const followingText = textNode.data.slice(endOffset);
      const next = textNode.nextSibling;
      parentEl.removeChild(textNode);
      if (precedingText) parentEl.insertBefore(document.createTextNode(precedingText), next);
      parentEl.insertBefore(span, next);
      if (followingText) parentEl.insertBefore(document.createTextNode(followingText), next);
      this.expandedEl = span;
      this.expandedElOriginalText = rawText;
      const spanText = span.firstChild;
      if (spanText) {
        const sel = window.getSelection();
        const r = document.createRange();
        r.setStart(spanText, rawText.length - 1);
        r.collapse(true);
        sel.removeAllRanges();
        sel.addRange(r);
      }
    } finally {
      this.isModifyingDom = false;
    }
    this.savedRange = null;
    return true;
  }
  // Wraps the selected text in a tate-chu-yoko element
  wrapSelectionWithTcy() {
    return this.wrapSelectionWith(createTcyEl);
  }
  // Wraps the selected text in a bouten element
  wrapSelectionWithBouten() {
    return this.wrapSelectionWith(createBoutenEl);
  }
  // Handles ArrowUp (→ move left) and ArrowDown (→ move right) when cursor is inside a tcy span.
  // In vertical writing mode the tcy element is laid out horizontally, so the vertical arrow keys
  // should navigate within the tcy text rather than jumping to the adjacent line.
  // Returns true if the key was consumed (caller should call preventDefault).
  handleTcyNavigation(key) {
    if (key !== "ArrowUp" && key !== "ArrowDown") return false;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return false;
    const range = sel.getRangeAt(0);
    const tcySpan = findTcyAncestor(range.startContainer, this.el);
    if (!tcySpan) return false;
    const moveLeft = key === "ArrowUp";
    const textNode = tcySpan.firstChild instanceof Text ? tcySpan.firstChild : null;
    const r = document.createRange();
    if (!textNode) {
      if (moveLeft) r.setStartBefore(tcySpan);
      else r.setStartAfter(tcySpan);
      r.collapse(true);
      sel.removeAllRanges();
      sel.addRange(r);
      return true;
    }
    let currentOffset;
    if (range.startContainer === textNode) {
      currentOffset = range.startOffset;
    } else if (range.startContainer === tcySpan) {
      currentOffset = range.startOffset === 0 ? 0 : textNode.length;
    } else {
      return false;
    }
    const newOffset = currentOffset + (moveLeft ? -1 : 1);
    if (newOffset < 0) {
      r.setStartBefore(tcySpan);
    } else if (newOffset > textNode.length) {
      r.setStartAfter(tcySpan);
    } else {
      r.setStart(textNode, newOffset);
    }
    r.collapse(true);
    sel.removeAllRanges();
    sel.addRange(r);
    return true;
  }
  // Called on the beforeinput event (registered from view.ts).
  // Sets the inBurst flag to indicate there are uncommitted changes pending for CM6.
  onBeforeInput() {
    this.inBurst = true;
  }
  // Returns the bouten span that should intercept the next insertText event due to Chrome's
  // post-collapse cursor behavior, or null if not applicable.
  getCursorBoutenSpan() {
    return this.boutenGuard.getCursorBoutenSpan(this.expandBouten, this.expandedEl);
  }
  // Inserts chars into the DOM immediately after bouten without going through the Selection API.
  insertAfterBouten(bouten, chars) {
    this.boutenGuard.insertAfterBouten(bouten, chars);
  }
  // Called in compositionend (before commitToCm6) to move IME text that landed inside a
  // post-collapse bouten span out to after the span. Returns true if the DOM was changed.
  handleBoutenPostCollapseInput() {
    return this.boutenGuard.handleBoutenPostCollapseInput();
  }
  // Resets the burst flag after a commit. Does NOT clear boutenGuard.
  afterCommit() {
    this.inBurst = false;
  }
  // Resets the burst flag and clears boutenGuard on mouse click or navigation key.
  afterNavigation() {
    this.inBurst = false;
    this.boutenGuard.clear();
  }
  // ---- Shared logic for selection wrap ----
  // Shared implementation for element-replacement wraps (tcy, bouten, etc.)
  wrapSelectionWith(createElement) {
    if (this.expandedEl) return false;
    const resolved = this.resolveSelectionRange();
    if (!resolved) return false;
    const { textNode, startOffset, endOffset } = resolved;
    const selectedText = textNode.data.slice(startOffset, endOffset);
    if (!selectedText) return false;
    const newEl = createElement(selectedText);
    this.isModifyingDom = true;
    try {
      const inserted = insertAnnotationElement(textNode, startOffset, endOffset, newEl);
      this.anchorManager.ensureCursorAnchorAfter(inserted);
      const nextSib = inserted.nextSibling;
      const parentEl = inserted.parentElement;
      const sel = window.getSelection();
      if (parentEl && sel) this.placeCursorAfterCollapse(nextSib, parentEl, sel);
    } finally {
      this.isModifyingDom = false;
    }
    this.savedRange = null;
    return true;
  }
  // ---- Private helpers for inline expand/collapse ----
  // Walks up ancestors from node and returns the first expandable element (ruby or explicit tcy)
  findExpandableAncestor(node) {
    return this.expander.findExpandableAncestor(node, this.expandRuby, this.expandTcy, this.expandBouten);
  }
  // Expands target into a raw-text editing span and sets the cursor to the corresponding position
  expandForEditing(target, range) {
    const { el: span, originalText } = this.expander.expandForEditing(target, range);
    this.expandedEl = span;
    this.expandedElOriginalText = originalText;
    this.inBurst = false;
  }
  // Places the cursor just after a collapsed annotation element.
  // Inserts a cursor-anchor span at end-of-line if needed, and records boutenJustCollapsed.
  placeCursorAfterCollapse(nextSib, parentEl, sel) {
    var _a;
    this.anchorManager.placeCursorAfterCollapse(nextSib, parentEl, sel);
    if (nextSib == null ? void 0 : nextSib.isConnected) {
      const prevOfNextSib = nextSib.previousSibling;
      if (prevOfNextSib instanceof HTMLElement && prevOfNextSib.getAttribute("data-bouten")) {
        this.boutenGuard.set(prevOfNextSib, (_a = prevOfNextSib.textContent) != null ? _a : "");
      }
    }
  }
  // Called when Enter is pressed while expanded. Collapses and places cursor after the element.
  // Returns true if content changed (signal for view.ts to call commitToCm6).
  collapseForEnter() {
    if (!this.expandedEl) return false;
    const nextSib = this.expandedEl.nextSibling;
    const parentEl = this.expandedEl.parentElement;
    this.isModifyingDom = true;
    let changed = false;
    try {
      changed = this.collapseEditing();
      const sel = window.getSelection();
      if (parentEl && sel) this.placeCursorAfterCollapse(nextSib, parentEl, sel);
    } finally {
      this.isModifyingDom = false;
    }
    return changed;
  }
  // Collapses the editing span, re-parses its content, and inserts the result at the original position (caller handles cursor).
  // Returns true if content changed (signal for view.ts to call commitToCm6).
  collapseEditing() {
    if (!this.expandedEl) return false;
    const { hasChanged, detached } = this.expander.collapseEditing(
      this.expandedEl,
      this.expandedElOriginalText
    );
    this.expandedEl = null;
    this.expandedElOriginalText = null;
    if (!detached) this.inBurst = false;
    return hasChanged;
  }
  // Normalizes savedRange and returns { textNode, startOffset, endOffset }.
  resolveSelectionRange() {
    const r = this.savedRange;
    if (!r || r.startContainer.nodeType !== Node.TEXT_NODE) return null;
    const textNode = r.startContainer;
    if (r.endContainer === r.startContainer) {
      if (r.startOffset === r.endOffset) return null;
      return { textNode, startOffset: r.startOffset, endOffset: r.endOffset };
    }
    const parent = textNode.parentNode;
    if (!parent) return null;
    if (r.endContainer === parent) {
      const textNodeIdx = Array.from(parent.childNodes).indexOf(textNode);
      if (textNodeIdx !== -1 && r.endOffset > textNodeIdx) {
        return { textNode, startOffset: r.startOffset, endOffset: textNode.length };
      }
    }
    if (r.endContainer.nodeType === Node.ELEMENT_NODE && r.endContainer.tagName === "BR" && r.endContainer.parentNode === parent) {
      return { textNode, startOffset: r.startOffset, endOffset: textNode.length };
    }
    return null;
  }
  // Records the direction of the most recent navigation key so handleSelectionChange
  // can skip the U+200B placeholder in the correct direction.
  // Call from the keydown handler before the browser moves the cursor.
  notifyNavigationKey(key) {
    this.boutenGuard.clear();
    this.anchorManager.setSkipDirection(key);
  }
  // Called after input/compositionend when cursor may be inside a tate-cursor-anchor span.
  // Removes U+200B once real characters have been typed, or re-inserts it when the span is empty.
  handleCursorAnchorInput() {
    this.isModifyingDom = true;
    try {
      this.anchorManager.handleCursorAnchorInput();
    } finally {
      this.isModifyingDom = false;
    }
  }
};

// src/ui/InputTransformer.ts
var OPEN_BRACKETS = /* @__PURE__ */ new Set([
  "\u300C",
  // 「
  "\u300E",
  // 『
  "\u3010",
  // 【
  "\u3014",
  // 〔
  "\uFF08",
  // （
  "\uFF5B",
  // ｛
  "\u3008",
  // 〈
  "\u300A",
  // 《
  "\u3016",
  // 〖
  "\u3018",
  // 〘
  "\u301A"
  // 〚
]);
var InputTransformer = class {
  constructor(el, settings) {
    this.el = el;
    this.settings = { ...settings };
  }
  updateSettings(settings) {
    this.settings = { ...settings };
  }
  applySpaceConversion(char) {
    return this.settings.convertHalfWidthSpace && char === " " ? "\u3000" : char;
  }
  // Called on compositionstart. Inserts one indent space at line start before IME composition begins
  // so that Japanese characters are typed after the indent, not before it.
  handleCompositionStart() {
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    const range = sel.getRangeAt(0);
    const textBefore = this.getTextBeforeCursorInParagraph(range);
    if (textBefore !== "") return;
    if (this.settings.autoIndentOnInput) {
      this.insertText(range, "\u3000");
    }
  }
  // Called on compositionend. Removes one leading full-width space when the confirmed character
  // is a full-width opening bracket preceded only by full-width spaces in the paragraph.
  handleCompositionEnd() {
    if (!this.settings.removeBracketIndent) return;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    const range = sel.getRangeAt(0);
    if (!range.collapsed) return;
    const { startContainer, startOffset } = range;
    if (startContainer.nodeType !== Node.TEXT_NODE) return;
    const textNode = startContainer;
    if (startOffset === 0) return;
    const charBefore = textNode.data[startOffset - 1];
    if (!OPEN_BRACKETS.has(charBefore)) return;
    const bracketRange = document.createRange();
    bracketRange.setStart(textNode, startOffset - 1);
    bracketRange.collapse(true);
    const textBeforeBracket = this.getTextBeforeCursorInParagraph(bracketRange);
    if (textBeforeBracket.length === 0) return;
    if (!/^\u3000+$/.test(textBeforeBracket)) return;
    this.removeOneLeadingFullWidthSpace(range);
  }
  // Called from EditorElement.onBeforeInput. Intercepts insertText events and applies
  // space conversion, auto-indent, and bracket de-indent according to current settings.
  handleBeforeInput(e) {
    if (e.inputType !== "insertText" || !e.data || e.isComposing) return;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    const range = sel.getRangeAt(0);
    let char = e.data;
    if (this.settings.convertHalfWidthSpace && char === " ") {
      char = "\u3000";
    }
    const textBefore = this.getTextBeforeCursorInParagraph(range);
    const isAtLineStart = textBefore === "";
    const leadingSpacesBeforeCursor = /^\u3000*$/.test(textBefore) ? textBefore.length : 0;
    if (isAtLineStart && char !== "\u3000") {
      let indentCount = this.settings.autoIndentOnInput ? 1 : 0;
      if (this.settings.removeBracketIndent && OPEN_BRACKETS.has(char)) {
        indentCount = Math.max(0, indentCount - 1);
      }
      if (char !== e.data || indentCount > 0) {
        e.preventDefault();
        this.insertText(range, "\u3000".repeat(indentCount) + char);
      }
      return;
    }
    if (leadingSpacesBeforeCursor >= 1 && this.settings.removeBracketIndent && OPEN_BRACKETS.has(char)) {
      e.preventDefault();
      this.removeOneLeadingFullWidthSpace(range);
      const newSel = window.getSelection();
      if (newSel && newSel.rangeCount > 0) {
        this.insertText(newSel.getRangeAt(0), char);
      }
      return;
    }
    if (char !== e.data) {
      e.preventDefault();
      this.insertText(range, char);
    }
  }
  // ---- Private helpers ----
  getTextBeforeCursorInParagraph(range) {
    const div = this.getContainingParagraphDiv(range.startContainer);
    if (!div) return "";
    try {
      const lineRange = document.createRange();
      lineRange.setStart(div, 0);
      lineRange.setEnd(range.startContainer, range.startOffset);
      return lineRange.toString();
    } catch (e) {
      return "";
    }
  }
  getContainingParagraphDiv(node) {
    let current = node;
    while (current && current !== this.el) {
      if (current.nodeType === Node.ELEMENT_NODE && current.tagName === "DIV" && current.parentNode === this.el) {
        return current;
      }
      current = current.parentNode;
    }
    return null;
  }
  // Called after Enter (insertParagraph). Inserts N full-width spaces matching the preceding paragraph's
  // leading indent. Only active when matchPrecedingIndent is enabled.
  handleParagraphInsert() {
    if (!this.settings.matchPrecedingIndent) return;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    const range = sel.getRangeAt(0);
    const indentCount = this.getPrecedingParagraphLeadingSpaces(range);
    if (indentCount > 0) {
      this.insertText(range, "\u3000".repeat(indentCount));
    }
  }
  getPrecedingParagraphLeadingSpaces(range) {
    var _a;
    const currentDiv = this.getContainingParagraphDiv(range.startContainer);
    const prevDiv = currentDiv ? currentDiv.previousElementSibling : this.el.lastElementChild;
    if (!prevDiv || prevDiv.tagName !== "DIV") return 0;
    const walker = document.createTreeWalker(prevDiv, NodeFilter.SHOW_TEXT);
    let firstText = walker.nextNode();
    while (firstText && firstText.data.length === 0) firstText = walker.nextNode();
    const text = (_a = firstText == null ? void 0 : firstText.data) != null ? _a : "";
    let count = 0;
    while (count < text.length && text[count] === "\u3000") count++;
    return count;
  }
  removeOneLeadingFullWidthSpace(cursorRange) {
    var _a;
    const div = (_a = this.getContainingParagraphDiv(cursorRange.startContainer)) != null ? _a : this.el;
    const walker = document.createTreeWalker(div, NodeFilter.SHOW_TEXT);
    let firstText = walker.nextNode();
    while (firstText && firstText.data.length === 0) firstText = walker.nextNode();
    if (!firstText || firstText.data[0] !== "\u3000") return;
    firstText.deleteData(0, 1);
    if (cursorRange.startContainer === firstText) {
      const newOffset = Math.max(0, cursorRange.startOffset - 1);
      const r = document.createRange();
      r.setStart(firstText, newOffset);
      r.collapse(true);
      const sel = window.getSelection();
      if (sel) {
        sel.removeAllRanges();
        sel.addRange(r);
      }
    }
  }
  insertText(range, text) {
    range.deleteContents();
    if (range.startContainer.nodeType === Node.TEXT_NODE) {
      const node = range.startContainer;
      const insertOffset = range.startOffset;
      node.insertData(insertOffset, text);
      const r = document.createRange();
      r.setStart(node, insertOffset + text.length);
      r.collapse(true);
      const sel = window.getSelection();
      if (sel) {
        sel.removeAllRanges();
        sel.addRange(r);
      }
    } else {
      const textNode = document.createTextNode(text);
      range.insertNode(textNode);
      range.setStartAfter(textNode);
      range.collapse(true);
      const sel = window.getSelection();
      if (sel) {
        sel.removeAllRanges();
        sel.addRange(range);
      }
    }
  }
};

// src/ui/EditorElement.ts
var EditorElement = class {
  constructor(container) {
    this.el = container.createEl("div");
    this.el.addClass("tate-editor");
    this.el.setAttribute("contenteditable", "true");
    this.el.setAttribute("spellcheck", "false");
    this.el.setAttribute("data-placeholder", "\u30D5\u30A1\u30A4\u30EB\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044");
    this.inlineEditor = new InlineEditor(this.el);
    this.inputTransformer = new InputTransformer(this.el, DEFAULT_SETTINGS);
  }
  getValue() {
    return Array.from(this.el.childNodes).map((n) => serializeNode(n, this.el)).join("");
  }
  setValue(content, preserveCursor) {
    this.inlineEditor.reset();
    if (this.getValue() === content && this.el.childNodes.length > 0) return;
    if (preserveCursor && document.activeElement === this.el) {
      const pos = this.getVisibleOffset();
      this.el.replaceChildren((0, import_obsidian3.sanitizeHTMLToDom)(parseToHtml(content)));
      this.setVisibleOffset(pos);
    } else {
      this.el.replaceChildren((0, import_obsidian3.sanitizeHTMLToDom)(parseToHtml(content)));
    }
  }
  // ---- Inline expand/collapse (call from selectionchange) ----
  handleSelectionChange() {
    return this.inlineEditor.handleSelectionChange();
  }
  collapseForEnter() {
    return this.inlineEditor.collapseForEnter();
  }
  // ---- Ruby / tcy live conversion (call from input/compositionend) ----
  handleRubyCompletion() {
    return this.inlineEditor.handleRubyCompletion();
  }
  handleTcyCompletion() {
    return this.inlineEditor.handleTcyCompletion();
  }
  handleBoutenCompletion() {
    return this.inlineEditor.handleBoutenCompletion();
  }
  // ---- Selection wrap methods called from the command palette ----
  wrapSelectionWithRuby() {
    return this.inlineEditor.wrapSelectionWithRuby();
  }
  wrapSelectionWithTcy() {
    return this.inlineEditor.wrapSelectionWithTcy();
  }
  wrapSelectionWithBouten() {
    return this.inlineEditor.wrapSelectionWithBouten();
  }
  // Copy handler: serializes the selected DOM to Aozora notation and writes it to text/plain.
  // This ensures ruby/tcy/bouten are preserved when copying within the editor.
  handleCopy(e) {
    this.serializeSelectionToClipboard(e);
  }
  // Cut handler: same as copy, then deletes the selected content.
  handleCut(e) {
    const range = this.serializeSelectionToClipboard(e);
    if (!range) return;
    range.deleteContents();
  }
  // Serializes the current selection to Aozora notation and writes it to text/plain.
  // Returns the range on success (for cut to delete), or null if nothing to serialize.
  serializeSelectionToClipboard(e) {
    var _a;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return null;
    const range = sel.getRangeAt(0);
    if (range.collapsed || !this.el.contains(range.commonAncestorContainer)) return null;
    e.preventDefault();
    const fragment = range.cloneContents();
    const text = Array.from(fragment.childNodes).map((n) => serializeNode(n, this.el)).join("");
    (_a = e.clipboardData) == null ? void 0 : _a.setData("text/plain", text);
    return range;
  }
  // Paste handler: parses Aozora notation in the pasted text and inserts rendered inline elements.
  // Multi-line paste creates one <div> per line (matching Enter-key paragraph behavior).
  handlePaste(e) {
    var _a, _b;
    e.preventDefault();
    const text = (_b = (_a = e.clipboardData) == null ? void 0 : _a.getData("text/plain")) != null ? _b : "";
    if (!text) return;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return;
    const range = sel.getRangeAt(0);
    range.deleteContents();
    const lines = text.split("\n");
    if (lines.length === 1) {
      this.insertParsedInline(range, lines[0]);
    } else {
      this.insertParsedParagraphs(range, lines);
    }
    this.inlineEditor.onBeforeInput();
  }
  // Inserts parsed Aozora inline elements at the range position (single-line paste).
  insertParsedInline(range, line) {
    const sel = window.getSelection();
    if (line) {
      const frag = (0, import_obsidian3.sanitizeHTMLToDom)(parseInlineToHtml(line));
      for (const node of Array.from(frag.childNodes)) {
        range.insertNode(node);
        range.setStartAfter(node);
        range.collapse(true);
      }
    }
    sel.removeAllRanges();
    sel.addRange(range);
  }
  // Inserts parsed lines as separate paragraph <div>s (multi-line paste).
  // Splits the current paragraph at the cursor: first line appends to it,
  // each remaining line becomes a new <div>, and after-cursor content moves to the last.
  insertParsedParagraphs(range, lines) {
    const sel = window.getSelection();
    const paragraphDiv = this.findParagraphDiv(range.startContainer);
    if (!paragraphDiv || this.inlineEditor.isExpanded()) {
      for (let i = 0; i < lines.length; i++) {
        if (i > 0) {
          const br = document.createElement("br");
          range.insertNode(br);
          range.setStartAfter(br);
          range.collapse(true);
        }
        if (lines[i]) {
          const frag = (0, import_obsidian3.sanitizeHTMLToDom)(parseInlineToHtml(lines[i]));
          for (const node of Array.from(frag.childNodes)) {
            range.insertNode(node);
            range.setStartAfter(node);
            range.collapse(true);
          }
        }
      }
      sel.removeAllRanges();
      sel.addRange(range);
      return;
    }
    const afterRange = document.createRange();
    afterRange.selectNodeContents(paragraphDiv);
    afterRange.setStart(range.startContainer, range.startOffset);
    const afterFragment = afterRange.extractContents();
    const firstFrag = (0, import_obsidian3.sanitizeHTMLToDom)(parseInlineToHtml(lines[0]));
    paragraphDiv.append(...Array.from(firstFrag.childNodes));
    let insertAfter = paragraphDiv;
    let lastPastedNode = null;
    for (let i = 1; i < lines.length; i++) {
      const div = document.createElement("div");
      const lineFrag = (0, import_obsidian3.sanitizeHTMLToDom)(parseInlineToHtml(lines[i]));
      const lineNodes = Array.from(lineFrag.childNodes);
      div.append(...lineNodes);
      lastPastedNode = lineNodes.length > 0 ? lineNodes[lineNodes.length - 1] : null;
      if (i === lines.length - 1) {
        div.append(...Array.from(afterFragment.childNodes));
      }
      insertAfter.after(div);
      insertAfter = div;
    }
    const newRange = document.createRange();
    if (lastPastedNode) {
      newRange.setStartAfter(lastPastedNode);
    } else {
      newRange.setStart(insertAfter, 0);
    }
    newRange.collapse(true);
    sel.removeAllRanges();
    sel.addRange(newRange);
  }
  // Returns the direct <div> child of this.el that contains node, or null.
  findParagraphDiv(node) {
    let current = node;
    while (current && current !== this.el) {
      if (current.parentElement === this.el && current instanceof HTMLElement && current.tagName === "DIV") {
        return current;
      }
      current = current.parentElement;
    }
    return null;
  }
  // Restores a minimal <div><br></div> if Chrome deleted all paragraph divs (e.g., Backspace on last char).
  normalizeEmptyDom() {
    if (this.el.childNodes.length > 0) return;
    const div = document.createElement("div");
    div.appendChild(document.createElement("br"));
    this.el.appendChild(div);
    const range = document.createRange();
    range.setStart(div, 0);
    range.collapse(true);
    const sel = window.getSelection();
    if (sel) {
      sel.removeAllRanges();
      sel.addRange(range);
    }
  }
  // Clears all content and shows the placeholder (used when no file is active).
  clearContent() {
    this.inlineEditor.reset();
    this.el.replaceChildren();
  }
  applySettings(settings) {
    this.el.style.fontFamily = settings.fontFamily;
    this.el.style.fontSize = `${settings.fontSize}px`;
    this.el.style.lineBreak = settings.lineBreak;
    this.inputTransformer.updateSettings(settings);
    this.inlineEditor.setExpandSettings(
      settings.expandRubyInline,
      settings.expandTcyInline,
      settings.expandBoutenInline
    );
  }
  adjustWidth() {
  }
  focus() {
    this.el.focus();
  }
  // Called on beforeinput event (registered from view.ts).
  // For non-IME insertText when cursor is inside a post-collapse bouten span
  // (Chrome normalized it back in), intercepts the event and inserts the character
  // after the span instead. Chrome's Selection API normalization is synchronous and
  // cannot be countered with sel.addRange, so Range-level insertion is used instead.
  onBeforeInput(e) {
    this.inlineEditor.onBeforeInput();
    if (!e.isComposing && e.inputType === "insertText" && e.data) {
      const boutenSpan = this.inlineEditor.getCursorBoutenSpan();
      if (boutenSpan) {
        e.preventDefault();
        const char = this.inputTransformer.applySpaceConversion(e.data);
        this.inlineEditor.insertAfterBouten(boutenSpan, char);
        return;
      }
    }
    this.inputTransformer.handleBeforeInput(e);
  }
  // Called after Enter (insertParagraph input event) from view.ts.
  handleParagraphInsert() {
    this.inputTransformer.handleParagraphInsert();
  }
  // Called on compositionstart (registered from view.ts).
  onCompositionStart() {
    this.inputTransformer.handleCompositionStart();
  }
  // Called in compositionend (before commitToCm6) to move IME text that landed inside a
  // post-collapse bouten span out to after the span. Returns true if the DOM was changed.
  handleBoutenPostCollapseInput() {
    return this.inlineEditor.handleBoutenPostCollapseInput();
  }
  // Called on compositionend (registered from view.ts), before commitToCm6.
  onCompositionEnd() {
    this.inputTransformer.handleCompositionEnd();
  }
  // Resets the burst flag after a commit. Does NOT clear boutenGuard.
  afterCommit() {
    this.inlineEditor.afterCommit();
  }
  // Resets the burst flag and clears boutenGuard on mouse click or navigation key.
  afterNavigation() {
    this.inlineEditor.afterNavigation();
  }
  // Called after CM6 Undo/Redo. Applies content to the vertical writing view and
  // restores the cursor by converting srcOffset (CM6 cursor position) via srcToView.
  applyFromCm6(content, srcOffset) {
    this.inlineEditor.reset();
    if (this.getValue() !== content) {
      this.el.replaceChildren((0, import_obsidian3.sanitizeHTMLToDom)(parseToHtml(content)));
    }
    const segs = buildSegmentMap(content);
    const viewOffset = srcToView(segs, srcOffset);
    this.setVisibleOffset(viewOffset);
  }
  /** Returns whether a tate-editing span is currently expanded (used by view.ts to decide cursor sync). */
  isInlineExpanded() {
    return this.inlineEditor.isExpanded();
  }
  /** Returns the current cursor position in the vertical writing view as a visible offset (used by view.ts for cursor sync). */
  getViewCursorOffset() {
    return this.getVisibleOffset();
  }
  // Called after input/compositionend to manage U+200B in the cursor anchor span.
  handleCursorAnchorInput() {
    this.inlineEditor.handleCursorAnchorInput();
  }
  // Records the direction of the most recent navigation key for anchor skip.
  notifyNavigationKey(key) {
    this.inlineEditor.notifyNavigationKey(key);
  }
  // Intercepts ArrowUp/ArrowDown inside a tcy span and moves the cursor left/right instead.
  // Returns true if the key was consumed (caller should call preventDefault).
  handleTcyNavigation(key) {
    return this.inlineEditor.handleTcyNavigation(key);
  }
  // ---- Cursor operations (offset managed in visible character count, excluding <rt> and U+200B) ----
  getVisibleOffset() {
    var _a, _b;
    const sel = window.getSelection();
    if (!sel || sel.rangeCount === 0) return 0;
    const range = sel.getRangeAt(0);
    let count = 0;
    const walker = document.createTreeWalker(this.el, NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      if (node === range.startContainer) {
        if (!this.isInsideRt(node)) {
          const text = (_a = node.textContent) != null ? _a : "";
          const beforeCursor = this.isInsideAnchorSpan(node) ? text.slice(0, range.startOffset).replace(/\u200B/g, "").length : range.startOffset;
          count += beforeCursor;
        }
        break;
      }
      if (!this.isInsideRt(node)) {
        count += this.isInsideAnchorSpan(node) ? ((_b = node.textContent) != null ? _b : "").replace(/\u200B/g, "").length : node.length;
      }
      node = walker.nextNode();
    }
    return count;
  }
  setVisibleOffset(offset) {
    var _a, _b;
    const sel = window.getSelection();
    if (!sel) return;
    let remaining = offset;
    const walker = document.createTreeWalker(this.el, NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      if (!this.isInsideRt(node)) {
        const visLen = this.isInsideAnchorSpan(node) ? ((_a = node.textContent) != null ? _a : "").replace(/\u200B/g, "").length : node.length;
        if (remaining <= visLen) {
          const range2 = document.createRange();
          let actualOffset;
          if (this.isInsideAnchorSpan(node)) {
            const text = (_b = node.textContent) != null ? _b : "";
            actualOffset = 0;
            let visible = 0;
            for (let i = 0; i < text.length; i++) {
              if (visible === remaining) {
                actualOffset = i;
                break;
              }
              if (text[i] !== "\u200B") visible++;
              actualOffset = i + 1;
            }
          } else {
            actualOffset = remaining;
          }
          range2.setStart(node, actualOffset);
          range2.collapse(true);
          sel.removeAllRanges();
          sel.addRange(range2);
          return;
        }
        remaining -= visLen;
      }
      node = walker.nextNode();
    }
    const range = document.createRange();
    range.selectNodeContents(this.el);
    range.collapse(false);
    sel.removeAllRanges();
    sel.addRange(range);
  }
  isInsideRt(node) {
    let parent = node.parentElement;
    while (parent && parent !== this.el) {
      if (parent.tagName === "RT") return true;
      parent = parent.parentElement;
    }
    return false;
  }
  isInsideAnchorSpan(node) {
    let parent = node.parentElement;
    while (parent && parent !== this.el) {
      if (parent.classList.contains("tate-cursor-anchor")) return true;
      parent = parent.parentElement;
    }
    return false;
  }
};

// src/view.ts
var TATE_VIEW_TYPE = "tate-vertical-writing";
var VerticalWritingView = class _VerticalWritingView extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.editorEl = null;
    this.syncCoordinator = null;
    // Last committed text written to CM6.
    // Used for comparison in onExternalModify to avoid confusion with getValue() which may contain uncommitted IME text.
    this.lastCommittedContent = "";
  }
  getViewType() {
    return TATE_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u7E26\u66F8\u304D";
  }
  getIcon() {
    return "tally-3";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("tate-container");
    const editorEl = new EditorElement(container);
    this.editorEl = editorEl;
    editorEl.applySettings(this.plugin.settings);
    const syncCoordinator = new SyncCoordinator(
      this.app.vault,
      // Use committed text for comparison (not getValue() which may contain uncommitted IME text)
      () => this.lastCommittedContent,
      (content, preserveCursor) => {
        this.lastCommittedContent = content;
        editorEl.setValue(content, preserveCursor);
        this.plugin.updateCharCount(countChars(content));
      }
    );
    this.syncCoordinator = syncCoordinator;
    this.registerDomEvent(editorEl.el, "copy", (e) => {
      editorEl.handleCopy(e);
    });
    this.registerDomEvent(editorEl.el, "cut", (e) => {
      if (!this.guardCm6(e)) return;
      editorEl.handleCut(e);
      this.commitToCm6();
    });
    this.registerDomEvent(editorEl.el, "paste", (e) => {
      if (!this.guardCm6(e)) return;
      editorEl.handlePaste(e);
      this.commitToCm6();
    });
    this.registerDomEvent(editorEl.el, "beforeinput", (e) => {
      if (!this.guardCm6(e)) return;
      if (!e.isComposing && e.inputType === "insertParagraph" && editorEl.isInlineExpanded()) {
        e.preventDefault();
        const contentChanged = editorEl.collapseForEnter();
        if (contentChanged) this.commitToCm6();
        return;
      }
      editorEl.onBeforeInput(e);
    });
    this.registerDomEvent(editorEl.el, "input", (e) => {
      editorEl.normalizeEmptyDom();
      const inputEvent = e;
      if (!inputEvent.isComposing) {
        if (inputEvent.inputType === "insertParagraph") {
          editorEl.handleParagraphInsert();
          this.commitToCm6();
          return;
        }
        const annotated = editorEl.handleRubyCompletion() || editorEl.handleTcyCompletion() || editorEl.handleBoutenCompletion();
        if (annotated) this.commitToCm6();
        editorEl.handleCursorAnchorInput();
      }
    });
    this.registerDomEvent(editorEl.el, "compositionstart", () => {
      if (!this.getCm6Editor()) return;
      editorEl.onCompositionStart();
    });
    this.registerDomEvent(editorEl.el, "compositionend", () => {
      editorEl.handleRubyCompletion();
      editorEl.handleTcyCompletion();
      editorEl.handleBoutenCompletion();
      editorEl.onCompositionEnd();
      editorEl.handleCursorAnchorInput();
      editorEl.handleBoutenPostCollapseInput();
      this.commitToCm6();
    });
    this.registerDomEvent(document, "selectionchange", () => {
      const contentChanged = editorEl.handleSelectionChange();
      if (contentChanged) this.commitToCm6();
    });
    this.registerDomEvent(editorEl.el, "mousedown", () => {
      this.commitToCm6();
      editorEl.afterNavigation();
    });
    this.registerDomEvent(editorEl.el, "keydown", (e) => {
      if ((e.metaKey || e.ctrlKey) && !e.altKey && e.key === "z") {
        e.preventDefault();
        this.doUndoRedo(editorEl, e.shiftKey);
        return;
      }
      if (!e.isComposing && (e.key === "ArrowUp" || e.key === "ArrowDown")) {
        if (editorEl.handleTcyNavigation(e.key)) {
          e.preventDefault();
          this.commitToCm6();
          editorEl.afterNavigation();
          return;
        }
      }
      if (!e.isComposing && [
        "ArrowLeft",
        "ArrowRight",
        "ArrowUp",
        "ArrowDown",
        "Home",
        "End",
        "PageUp",
        "PageDown"
      ].includes(e.key)) {
        editorEl.notifyNavigationKey(e.key);
        this.commitToCm6();
        editorEl.afterNavigation();
      }
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian4.TFile) void syncCoordinator.onExternalModify(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian4.TFile) syncCoordinator.onFileDelete(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian4.TFile) syncCoordinator.onFileRename(file, oldPath);
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file === syncCoordinator.currentFile) return;
        if (!file) {
          syncCoordinator.clearCurrentFile();
          editorEl.clearContent();
          this.lastCommittedContent = "";
          this.plugin.updateCharCount(null);
          return;
        }
        void syncCoordinator.loadFile(file);
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (leaf === null) return;
        if (leaf === this.leaf) {
          this.plugin.updateCharCount(countChars(this.lastCommittedContent));
        } else if (!this.app.workspace.getLeavesOfType(TATE_VIEW_TYPE).includes(leaf)) {
          this.plugin.updateCharCount(null);
        }
      })
    );
    await this.loadInitialFile(syncCoordinator);
  }
  async loadInitialFile(syncCoordinator) {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      await syncCoordinator.loadFile(activeFile);
      return;
    }
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      if (leaf.view instanceof import_obsidian4.MarkdownView && leaf.view.file) {
        await syncCoordinator.loadFile(leaf.view.file);
        return;
      }
    }
  }
  onClose() {
    var _a;
    this.commitToCm6();
    (_a = this.syncCoordinator) == null ? void 0 : _a.dispose();
    if (!this.app.workspace.getActiveViewOfType(_VerticalWritingView)) {
      this.plugin.updateCharCount(null);
    }
    return Promise.resolve();
  }
  applySettings(settings) {
    var _a;
    (_a = this.editorEl) == null ? void 0 : _a.applySettings(settings);
  }
  applyRuby() {
    if (!this.editorEl) return;
    if (!this.editorEl.wrapSelectionWithRuby()) {
      new import_obsidian4.Notice("\u30C6\u30AD\u30B9\u30C8\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044");
    }
  }
  applyTcy() {
    this.applyAnnotation((el) => el.wrapSelectionWithTcy());
  }
  applyBouten() {
    this.applyAnnotation((el) => el.wrapSelectionWithBouten());
  }
  applyAnnotation(wrap) {
    if (!this.editorEl) return;
    if (!wrap(this.editorEl)) {
      new import_obsidian4.Notice("\u30C6\u30AD\u30B9\u30C8\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044");
    } else {
      this.commitToCm6();
    }
  }
  // ---- CM6 integration helpers ----
  /** Returns the CM6 editor for the MarkdownView currently showing currentFile, or null if not found. */
  getCm6Editor() {
    var _a;
    const file = (_a = this.syncCoordinator) == null ? void 0 : _a.currentFile;
    if (!file) return null;
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const mv = leaf.view;
      if (mv instanceof import_obsidian4.MarkdownView && mv.file === file) {
        return mv.editor;
      }
    }
    return null;
  }
  /** Cancels the input event and shows a Notice if the CM6 editor is unavailable.
   *  Returns true if CM6 is available. */
  guardCm6(e) {
    if (this.getCm6Editor()) return true;
    e.preventDefault();
    new import_obsidian4.Notice("\u7E26\u66F8\u304D\u30A8\u30C7\u30A3\u30BF\u3092\u4F7F\u7528\u3059\u308B\u306B\u306F\u3001\u5BFE\u5FDC\u3059\u308B Markdown \u30D3\u30E5\u30FC\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044");
    return false;
  }
  /** Commits the current content of the vertical writing editor to CM6 using differential replaceRange.
   *  Only the changed region (excluding identical leading/trailing characters) is replaced.
   *  This lets CM6 record the exact edit position so the cursor lands at the edit site after Undo.
   *  When content changes, the CM6 cursor is also synced to the vertical writing view cursor.
   *  Cursor sync is skipped while tate-editing is expanded (synced via selectionchange on collapse). */
  commitToCm6() {
    const el = this.editorEl;
    if (!el) return;
    const cm6 = this.getCm6Editor();
    if (!cm6) return;
    const content = el.getValue();
    const cm6Content = cm6.getValue();
    if (content === cm6Content) return;
    let fromStart = 0;
    while (fromStart < cm6Content.length && fromStart < content.length && cm6Content[fromStart] === content[fromStart]) {
      fromStart++;
    }
    let fromEndOld = cm6Content.length;
    let fromEndNew = content.length;
    while (fromEndOld > fromStart && fromEndNew > fromStart && cm6Content[fromEndOld - 1] === content[fromEndNew - 1]) {
      fromEndOld--;
      fromEndNew--;
    }
    cm6.replaceRange(
      content.slice(fromStart, fromEndNew),
      cm6.offsetToPos(fromStart),
      cm6.offsetToPos(fromEndOld)
    );
    this.lastCommittedContent = content;
    const segs = buildSegmentMap(content);
    this.plugin.updateCharCount(segs.reduce((sum, seg) => sum + seg.viewLen, 0));
    if (!el.isInlineExpanded()) {
      const srcOffset = viewToSrc(segs, el.getViewCursorOffset());
      cm6.setCursor(cm6.offsetToPos(srcOffset));
    }
    el.afterCommit();
  }
  /** Delegates Undo (isRedo=false) or Redo (isRedo=true) to CM6 and restores
   *  the cursor position derived from the content diff.
   *  cm6.getCursor() is not used: after undo, getCursor() returns the position set by the
   *  last setCursor() call before the undone transaction, which may be unrelated to the edit site. */
  doUndoRedo(editorEl, isRedo) {
    const cm6 = this.getCm6Editor();
    if (!cm6) return;
    this.commitToCm6();
    const prevContent = this.lastCommittedContent;
    if (isRedo) cm6.redo();
    else cm6.undo();
    const newContent = cm6.getValue();
    if (newContent === prevContent) return;
    const srcOffset = this.deriveUndoRedoCursor(prevContent, newContent);
    editorEl.applyFromCm6(newContent, srcOffset);
    this.lastCommittedContent = newContent;
    this.plugin.updateCharCount(countChars(newContent));
  }
  /** Derives the appropriate cursor position from the content diff before and after undo/redo.
   *  Returns the end of the changed region in next (offset in next).
   *  undo (text restoration): end of restored text — e.g., undoing deletion of "うえお" → just after "お"
   *  redo (re-applying deletion): deletion point (start of changed region) — natural position for next input */
  deriveUndoRedoCursor(prev, next) {
    let fromStart = 0;
    while (fromStart < prev.length && fromStart < next.length && prev[fromStart] === next[fromStart]) {
      fromStart++;
    }
    let fromEndPrev = prev.length;
    let fromEndNext = next.length;
    while (fromEndPrev > fromStart && fromEndNext > fromStart && prev[fromEndPrev - 1] === next[fromEndNext - 1]) {
      fromEndPrev--;
      fromEndNext--;
    }
    return fromEndNext;
  }
};
function countChars(source) {
  return buildSegmentMap(source).reduce((sum, seg) => sum + seg.viewLen, 0);
}

// src/main.ts
var TatePlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.hide();
    const iconEl = this.statusBarItem.createEl("span", { cls: "tate-status-icon" });
    (0, import_obsidian5.setIcon)(iconEl, "tally-3");
    this.charCountEl = this.statusBarItem.createEl("span");
    this.registerView(
      TATE_VIEW_TYPE,
      (leaf) => new VerticalWritingView(leaf, this)
    );
    this.addCommand({
      id: "open-view",
      name: "\u7E26\u66F8\u304D\u30D3\u30E5\u30FC\u3092\u958B\u304F",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "add-ruby",
      name: "\u9078\u629E\u30C6\u30AD\u30B9\u30C8\u306B\u30EB\u30D3\u3092\u8A2D\u5B9A (ruby)",
      callback: () => this.dispatchToView((v) => v.applyRuby())
    });
    this.addCommand({
      id: "add-tcy",
      name: "\u9078\u629E\u30C6\u30AD\u30B9\u30C8\u3092\u7E26\u4E2D\u6A2A\u306B\u3059\u308B (tate-chu-yoko: tcy)",
      callback: () => this.dispatchToView((v) => v.applyTcy())
    });
    this.addCommand({
      id: "add-bouten",
      name: "\u9078\u629E\u30C6\u30AD\u30B9\u30C8\u306B\u508D\u70B9\u3092\u4ED8\u3051\u308B (bouten)",
      callback: () => this.dispatchToView((v) => v.applyBouten())
    });
    this.addSettingTab(new TateSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updateCharCount(count) {
    if (count === null) {
      this.statusBarItem.hide();
      return;
    }
    this.charCountEl.setText(count.toLocaleString() + "\u6587\u5B57");
    this.statusBarItem.show();
  }
  applySettingsToAllViews() {
    this.app.workspace.getLeavesOfType(TATE_VIEW_TYPE).forEach((leaf) => {
      if (leaf.view instanceof VerticalWritingView) {
        leaf.view.applySettings(this.settings);
      }
    });
  }
  dispatchToView(action) {
    const leaves = this.app.workspace.getLeavesOfType(TATE_VIEW_TYPE);
    if (leaves.length === 0) {
      new import_obsidian5.Notice("\u7E26\u66F8\u304D\u30D3\u30E5\u30FC\u304C\u958B\u3044\u3066\u3044\u307E\u305B\u3093");
      return;
    }
    action(leaves[0].view);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(TATE_VIEW_TYPE);
    if (existing.length > 0) {
      void this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: TATE_VIEW_TYPE, active: true });
    void this.app.workspace.revealLeaf(leaf);
  }
};
